### PR TITLE
Detect when full license text has been provided and preserve as separate field

### LINKED ISSUE #3088: Detect whether full license text or a license name has been provided
**What happened**:
I scanned an image of python, and one of the packages has a full description of the license.
here is an example:
```
        {
          "path": "/usr/local/lib/python3.9/site-packages/numpy-1.26.4.dist-info/RECORD",
          "layerID": "sha256:6baba55ee976c6469c4b3b5a3c4585320bc0da3e3c9638e2169195f7243b8d03",
          "accessPath": "/usr/local/lib/python3.9/site-packages/numpy-1.26.4.dist-info/RECORD",
          "annotations": {
            "evidence": "supporting"
          }
        }
      ],
      "licenses": [
        {
          "value": "Copyright (c) 2005-2023, NumPy Developers.\n All rights reserved.\n \n Redistribution and use in source and binary forms, with or without\n modification, are permitted provided that the following conditions are\n met:\n \n * Redistributions of source code must retain the above copyright\n notice, this list of conditions and the following disclaimer.\n \n * Redistributions in binary form must reproduce the above\n copyright notice, this list of conditions and the following\n disclaimer in the documentation and/or other materials provided\n with the distribution.\n \n * Neither the name of the NumPy Developers nor the names of any\n contributors may be used to endorse or promote products derived\n from this software without specific prior written permission.\n \n THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS\n \"AS IS\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT\n LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR\n A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT\n OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,\n SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT\n LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,\n DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY\n THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT\n (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
```
**What you expected to happen**:
In case license has \n inside of it, I think syft should trim it so it will not make the SBOM look weird.
**Steps to reproduce the issue**:
Here is the Dockerfile to build a sample of an image:
```
# Use the official Python 3.9 image from Docker Hub
FROM python:3.9

# Set the working directory in the container
WORKDIR /app

# Install the specific version of NumPy
RUN pip install numpy==1.26.4

# Specify the command to run on container start
CMD ["python"]
```

**Anything else we need to know?**:

**Environment**:
- Output of `syft version`: 1.9.0
- OS (e.g: `cat /etc/os-release` or similar): mac

### PR DESCRIPTION
**Pull request by spiffcs**
This PR updates the syft `License` model to include a new `FullText` field without any breaking changes to the current license behavior. We select candidates for this new field based on if the metadata being analyzed contains any new line characters. Because we still want `Value` to be populated as it is a required field I've included a default string that will be added here when `FullText` is the selected outcome for a newly constructed license.

- Fixes #3088, Partial #2724 (next step here is adding Scan Code DB to match full text against)

#### Verification

Use the following `Dockerfile` and build a test image
`docker build -t syft-3088:latest .`
```
# Use the official Python 3.9 image from Docker Hub
FROM python:3.9

# Set the working directory in the container
WORKDIR /app

# Install the specific version of NumPy
RUN pip install numpy==1.26.4

# Specify the command to run on container start
CMD ["python"]
```

Run the latest syft against this image using this branch:
`go run cmd/syft/main.go -o json syft-3088 | jq '.artifacts[] | select(.name=="numpy") | { name: .name, licenses: .licenses }'`

The large license value extracted from the package should now be listed under the field `fullText` with `value` being set to `FullText` to keep the field required and not incur any breaking changes.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have added unit tests that cover changed behavior
- [x] I have tested my code in common scenarios and confirmed there are no regressions
- [x] I have added comments to my code, particularly in hard-to-understand sections

### CODE REVIEW

File: syft/pkg/license.go [hunk 1]
```diff
@@ -12,6 +13,11 @@ import (
 	"github.com/anchore/syft/syft/license"
 )
 
+// FullTextValue is a placeholder value when license metadata is discovered to be fullText
+// A license with "FullText" in its value refers the consumer to look at the FullText field
+// This is so that we can keep Value as a required field up until syft 2.0
+var FullTextValue = "FullText"
```
Comment (wagoodman) [inline syft/pkg/license.go:19]: instead of a placeholder field that is attempting to have consumers reference the full text, should we just populate this with an empty value? That is, the json schema requires the field to be present but does not state that it must not be empty. I feel that if we don't know the ID we should leave this blank, but allow the new full text field to convey any discovered information. That way we can stay compliant to syft v1 json output but still add full text.

Comment (spiffcs) [reply syft/pkg/license.go:19]: When we do things like `otherLicenses` in SPDX what would we use for the license ID?

Comment (spiffcs) [reply syft/pkg/license.go:19]: @wagoodman - it looks like in syft we have a couple of places where we assume value should not be `""`

This includes the constructor for creating a license set:
https://github.com/anchore/syft/blob/02f9350fa53fdc8ccb3ad85bf77f103e70e1fb23/syft/pkg/license_set.go#L48-L64

If we were to keep this `const` as a placeholder some alternatives that @willmurphyscode and I discussed could be as follows:

#### Other Options for Value

- SeeFullText
- “<First_50_Characters of file> … [TRUNCATED]”

Do we want a better name for this `const` or do we want to go back and break up the license set/spdx formatter assumptions about `value` being present?

Comment (wagoodman) [reply syft/pkg/license.go:19]: I think this section will need to be updated already to account for filtering out "FullText" values. In that same way, can't we do the same for an empty value and the full text is specified in the other field?

**Comment by henrysachs** [comment]
I just hit this case and maybe this could get picked up again as the new field would help me a lot :)

**Comment by spiffcs** [comment]
> I just hit this case and maybe this could get picked up again as the new field would help me a lot :)

Yep! This is in the queue of a few other PR I have to clean up and get merged for the next up coming release. Apologies for the delay on this one.

**Comment by spiffcs** [comment]
Updating this in relation to https://github.com/anchore/syft/pull/3366

**Comment by Funsho-Agboola** [comment]
Hi team, great work on this. I have a primary issue #3780 which is about returning the full license strings in SPDX outputs instead of the LicenseRef-‹hash> identifiers as in [here](https://github.com/anchore/syft/blob/main/syft/format/internal/spdxutil/helpers/license.go). Can you consider extending this implementation to address this as well?

File: syft/pkg/license.go [hunk 2]
```diff
@@ -68,15 +74,31 @@ func NewLicense(value string) License {
...
-	var spdxExpression string
-	if value != "" {
+	var (
+		spdxExpression string
+		fullText       string
+	)
+	// Check parsed value for newline character to see if it's the full license text
+	// License: <HERE IS THE FULL TEXT> <Expressions>
+	// DO we want to also submit file name when determining fulltext
+	if strings.Contains(value, "\n") {
```
Comment (wagoodman) [inline syft/pkg/license.go:84]: may want to do a `value = strings.TrimSpace(value)` before this

File: syft/pkg/license_set.go [hunk 3]
```diff
@@ -50,15 +50,16 @@ func (s *LicenseSet) Add(licenses ...License) {
...
-				// doesn't exist, add it
-				s.set[id] = l
-			} else if err != nil {
-				log.Trace("license set failed to add license %#v: %+v", l, err)
-			}
+		if id, merged, err := s.addToExisting(l); err == nil && !merged {
+			// doesn't exist, add it
+			s.set[id] = l
+		} else if err != nil {
+			log.Trace("license set failed to add license %#v: %+v", l, err)
```
Comment (wagoodman) [inline syft/pkg/license_set.go:62]:
```suggestion
			log.WithFields("error", err, "license", l).Trace("failed to add license to license set")
```

File: syft/pkg/license.go [hunk 4]
```diff
@@ -25,9 +25,15 @@ var _ sort.Interface = (*Licenses)(nil)
...
+// If a license is given as it's full text in the metadata rather than it's value or SPDX expression
+
+// The FullText field is used to represent this data
+// A Concluded License type is the license the SBOM creator believes governs the package (human crafted or altered SBOM)
+// The Declared License is what the authors of a project believe govern the package. This is the default type syft declares.
 type License struct {
-	Value          string
 	SPDXExpression string
+	Value          string
+	FullText       string
```
Comment (wagoodman) [inline syft/pkg/license.go:36]: nit on naming: I don't think we should claim that the value is the "full text", but instead maybe just the "contents"

**Review by wagoodman — APPROVED** [review]

File: syft/pkg/license.go (hunk 4 above)
Comment (spiffcs) [reply syft/pkg/license.go:36]: These are good suggestions for 2.0 when we revisit the model again
