### PR TITLE
fixed #4529, parse and detect old bitnami img pkgs

### LINKED ISSUE #4529: old bitnami images without spdx files arent getting picked up correctly in the catalog
**What happened**:

the cataloger relies on spdx files, so when older bitnami images don’t have them, it skips over their packages and misses possible vulnerabilities

e.g

https://hub.docker.com/r/bitnamilegacy/mongodb/tags?name=4.4.11

**What you expected to happen**:

**Steps to reproduce the issue**:

**Anything else we need to know?**:

**Environment**:
- Output of `syft version`: latest 1.39.0
- OS (e.g: `cat /etc/os-release` or similar):

### PR DESCRIPTION
**Pull request by rezmoss**
## Description

fixed #4529, parse and detect old bitnami img pkgs

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (please discuss with the team first; Syft is 1.0 software and we won't accept breaking changes without going to 2.0)
- [ ] Documentation (updates the documentation)
- [ ] Chore (improve the developer experience, fix a test flake, etc, without changing the visible behavior of Syft)
- [ ] Performance (make Syft run faster or use less memory, without changing visible behavior much)

## Checklist

- [x] I have added unit tests that cover changed behavior
- [x] I have tested my code in common scenarios and confirmed there are no regressions
- [ ] I have added comments to my code, particularly in hard-to-understand sections

### CODE REVIEW

File: syft/pkg/cataloger/bitnami/cataloger.go [hunk 1]
```diff
@@ -23,6 +23,9 @@ func NewCataloger() pkg.Cataloger {
 	return generic.NewCataloger(catalogerName).
 		WithParserByGlobs(parseSBOM,
 			"/opt/bitnami/**/.spdx-*.spdx",
+		).
+		WithParserByGlobs(parseComponentsJSON,
+			"/opt/bitnami/.bitnami_components.json",
```
Comment (kzantow) [inline syft/pkg/cataloger/bitnami/cataloger.go:28]: is this always at `/opt/bitnami/..`? I guess we can always start specific and if needed make this a glob search 👍

File: syft/pkg/cataloger/bitnami/parse_components.go [hunk 2]
```diff
@@ -0,0 +1,100 @@
...
+		purl := packageurl.NewPackageURL(
+			"bitnami",
+			"",
+			name,
+			entry.Version,
+			qualifiers,
+			"",
+		).String()
+
+		metadata := &pkg.BitnamiSBOMEntry{
```
Comment (kzantow) [inline syft/pkg/cataloger/bitnami/parse_components.go:64]: Generally, we try to have metadata types that are very specific to the source material, and the SBOMEntry part makes this a little misleading, since these component definitions don't seem to be SBOMs, _exactly_. But if we made a different type it would be almost identical anyway, so this seems good to me (team agreed), just noting it.

**Review by kzantow — APPROVED** [review]
LGTM 👍
