### PR TITLE
reduce logging severity for non-Go binaries

### LINKED ISSUE #978: WARN golang cataloger: failed to read buildinfo
**What happened**:
In running an SPDX scan of some of my companies container images, it threw warnings. I am wanting to know if its a bug and if it means the SBOM is incomplete because of these WARNS

[0010] WARN golang cataloger: failed to read buildinfo (file="/usr/lib/python3.9/site-packages/orjson.libs/libgcc_s-eedded4b.so.1"): EOF
[0010] WARN golang cataloger: failed to read buildinfo (file="/usr/lib/python3.9/site-packages/orjson/orjson.cpython-39-x86_64-linux-musl.so"): EOF
[0023] WARN golang cataloger: failed to read buildinfo (file="/opt/google/chrome/nacl_helper_bootstrap"): EOF

**What you expected to happen**:
No WARNs

**How to reproduce it (as minimally and precisely as possible)**:
1. Install Docker Desktop for Mac
2. Install grype
brew tap anchore/grype
brew install grope
3. Download k10 images using k10 offline to your local docker repo

docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock \
    gcr.io/kasten-images/k10offline:4.5.14 pull images

run syft through all packages

syft registry.access.redhat.com/ubi8/ubi-minimal:8.5-240.1648458092 -o spdx > ubi-minimal:8.5-240.1648458092-spdx.out
syft emissaryingress/emissary:2.2.2 -o spdx > emissary:2.2.2-spdx.out
syft grafana/grafana:8.1.8 -o spdx > grafana:8.1.8-spdx.out
syft jimmidyson/configmap-reload:v0.5.0 -o spdx > configmap-reload:0.5.0-spdx.out
syft quay.io/prometheus/prometheus:v2.26.0 -o spdx > prometheus:4.5.14-spdx.out
syft gcr.io/kasten-images/auth:4.5.14 -o spdx > auth-spdx:4.5.14.out
syft gcr.io/kasten-images/upgrade:4.5.14 -o spdx > upgrade:4.5.14-spdx.out
syft gcr.io/kasten-images/catalog:4.5.14 -o spdx > catalog:4.5.14-spdx.out
syft ghcr.io/kanisterio/kanister-tools:0.78.0 -o spdx > kanister-tools:0.78.0-spdx.out
syft gcr.io/kasten-images/crypto:4.5.14 -o spdx > crypto:4.5.14-spdx.out
syft gcr.io/kasten-images/bloblifecyclemanager:4.5.14 -o spdx > bloblifecyclemanager:4.5.14-spdx.out
syft gcr.io/kasten-images/events:4.5.14 -o spdx > events:4.5.14-spdx.out
syft gcr.io/kasten-images/dashboardbff:4.5.14 -o spdx > dashboardbff:4.5.14-spdx.out
syft gcr.io/kasten-images/executor:4.5.14 -o spdx > executor:4.5.14-spdx.out
syft gcr.io/kasten-images/cephtool:4.5.14 -o spdx > cephtool:4.5.14-spdx.out
syft gcr.io/kasten-images/upgrade:4.5.14 -o spdx > upgrade:4.5.14-spdx.out
syft gcr.io/kasten-images/jobs:4.5.14 -o spdx > jobs:4.5.14-spdx.out
syft gcr.io/kasten-images/logging:4.5.14 -o spdx > logging:4.5.14-spdx.out
syft gcr.io/kasten-images/metering:4.5.14 -o spdx > metering:4.5.14-spdx.out
syft gcr.io/kasten-images/state:4.5.14 -o spdx > state:4.5.14-spdx.out
syft gcr.io/kasten-images/admin:4.5.14 -o spdx > admin:4.5.14-spdx.out
syft gcr.io/kasten-images/aggregatedapis:4.5.14 -o spdx > aggregatedapis:4.5.14-spdx.out
syft gcr.io/kasten-images/config:4.5.14 -o spdx > config:4.5.14-spdx.out
syft gcr.io/kasten-images/frontend:4.5.14 -o spdx > frontend:4.5.14-spdx.out
syft gcr.io/kasten-images/kanister:4.5.14 -o spdx > kanister:4.5.14-spdx.out

**Anything else we need to know?**:

**Environment**:
- Output of `syft version`:
- OS (e.g: `cat /etc/os-release` or similar):
joey.lei@c02fn5adml85 k10-imgs % syft version
Application:        syft
Version:            0.45.0
JsonSchemaVersion:  3.2.2
BuildDate:          2022-04-29T15:47:45Z
GitCommit:          36973021fad57baf443ffa88181394b87ce109a0
GitDescription:     v0.45.0
Platform:           darwin/amd64
GoVersion:          go1.18.1
Compiler:           gc

joey.lei@c02fn5adml85 k10-imgs % sw_vers 
ProductName:	macOS
ProductVersion:	12.3.1
BuildVersion:	21E258

### PR DESCRIPTION
**Pull request by luhring**
This is intended to be a temporary fix to the problem of excessive `WARN` logging when the Go binary cataloger encounters a non-Go binary.

Examples of noisy logging:

```console
[0011]  WARN golang cataloger: failed to read buildinfo (file="/usr/lib/python3.9/site-packages/orjson.libs/libgcc_s-eedded4b.so.1"): EOF
```

```console
[0012]  WARN golang cataloger: failed to read buildinfo (file=".vscode-test/vscode-1.48.1/Visual Studio Code.app/Contents/Resources/app/out/vs/platform/files/node/watcher/win32/CodeHelper.exe"): unrecognized file format
```

It should be noted that this change reduces the prominence of legitimate issues parsing real Go binaries. But from my experience, those cases seem to be in the minority, and what's been happening more often is that we're hitting non-Go binaries and then printing **_warnings_** to the user, when ideally we wouldn't be.

Fixes #978

### CODE REVIEW

File: syft/pkg/cataloger/golang/scan_bin.go [hunk 1]
```diff
@@ -41,7 +41,11 @@ func scanFile(reader unionReader, filename string) ([]*debug.BuildInfo, []string
 			}
 			// in this case we could not read the or parse the file, but not explicitly because it is not a
 			// go-compiled binary (though it still might be).
-			log.Warnf("golang cataloger: failed to read buildinfo (file=%q): %v", filename, err)
+			// TODO: We should change this back to "warn" eventually.
+			//  But right now it's catching too many cases where the reader IS NOT a Go binary at all.
+			//  It'd be great to see how we can get those cases to be detected and handled above before we get to
+			//  this point in execution.
+			log.Infof("golang cataloger: unable to read buildinfo (file=%q): %v", filename, err)
```
Comment (spiffcs) [inline syft/pkg/cataloger/golang/scan_bin.go:48]: @luhring just so I'm clear - you still think this should show up in its current state when a user passes `-v`?

Any consideration for going down to debug for `-vv` because of how many cases are being caught?

Comment (luhring) [reply syft/pkg/cataloger/golang/scan_bin.go:48]: That's a good question. I think this is a notable occurrence, so my personal opinion would be to have it show up w/ `-v`. I also think that ideally we move this back to `WARN` (so it shows up even without `-v`) — but only once we've solved the issue if this conditional branch being hit more correctly and less often.

I don't have a strong opinion on this, though. I see this as a temporary solution. I defer to you on this!

**Review by spiffcs — APPROVED** [review]
