### PR TITLE
Fixes #1179 Deprecated SPDX license

### LINKED ISSUE #1179: Deprecated SPDX license (GFDL* and BSD-2-Clause-NetBSD)
**What happened**:

This is a follow-up of #950.
The GPL family has been solved, but not all deprecated licenses. Please check the whole list of deprecated licenses at https://spdx.org/licenses/#Deprecated%20License%20Identifiers

**What you expected to happen**:

"GFDL-1.1" should be replaced by "GFDL-1.1-only"
"GFDL-1.2" should be replaced by "GFDL-1.2-only"
"GFDL-1.3" should be replaced by "GFDL-1.3-only"
"GFDL-1.1+" should be replaced by "GFDL-1.1-or-later"
"GFDL-1.2+" should be replaced by "GFDL-1.2-or-later"
"GFDL-1.3+" should be replaced by "GFDL-1.3-or-later"
"BSD-2-Clause-NetBSD " should be replaced by "BSD-2-Clause"

**How to reproduce it (as minimally and precisely as possible)**:

```
syft docker:apache/airflow:2.3.0b1-python3.10 -o spdx-tag-value > airflow-syft-0.54.0.spdx
```

**Anything else we need to know?**:

**Environment**:
- Output of `syft version`:

```
Application:        syft
Version:            0.54.0
JsonSchemaVersion:  3.3.2
BuildDate:          2022-08-17T18:56:00Z
GitCommit:          21eb77206020c04c9ca5316562e32179c73926a9
GitDescription:     v0.54.0
Platform:           linux/amd64
GoVersion:          go1.18.5
Compiler:           gc
```

- OS (e.g: `cat /etc/os-release` or similar):

```
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

### PR DESCRIPTION
**Pull request by vargenau**
Fixes #1179 Deprecated SPDX license (GFDL* and BSD-2-Clause-NetBSD)

Signed-off-by: Marc-Etienne Vargenau <marc-etienne.vargenau@nokia.com>

### CODE REVIEW

**Comment by kzantow** [comment]
Hi @vargenau, I made a bit of a change to this PR and regenerated the license list -- could you have a look through the result and confirm it is what you are expecting?

Thanks!

File: internal/spdxlicense/generate/generate_license_list_test.go [hunk 1]
```diff
@@ -22,18 +22,18 @@ func TestReplaceDeprecatedLicenses(t *testing.T) {
...
-		"abc-1.0.0":          "ABC-1.0-Only",
-		"abc-1.0-only":       "ABC-1.0-Only",
-		"abc-1.0.0-only":     "ABC-1.0-Only",
-		"abc-1+":             "ABC-1.0-Or-later",
-		"abc-1.0+":           "ABC-1.0-Or-later",
-		"abc-1.0.0+":         "ABC-1.0-Or-later",
-		"abc-1-or-later":     "ABC-1.0-Or-later",
-		"abc-1.0-or-later":   "ABC-1.0-Or-later",
-		"abc-1.0.0-or-later": "ABC-1.0-Or-later",
+		"abc-1":              "ABC-1.0-only",
```
Comment (spiffcs) [inline internal/spdxlicense/generate/generate_license_list_test.go:25]: Interesting that the casing has changed here, but just wanted to confirm for others who come across this that these are correct as of 3.18:

https://spdx.org/licenses/ <-- "or" and "only" are lower cased here

File: internal/spdxlicense/generate/license.go [hunk 2]
```diff
@@ -43,7 +60,7 @@ func (l License) canReplace(other License) bool {
 		}
 	}
 
-	return l.ID != other.ID
+	return l.ID == other.ID
```
Comment (spiffcs) [inline internal/spdxlicense/generate/license.go:63]: Why did we have to flip this here? I admit it's a little hard to reason about this case since it's the last one checked with so many other chances of an early return

**Review by spiffcs — COMMENTED** [review]
Just quick clarification comment -thanks @vargenau for the PR and @kzantow for the follow up here!

File: internal/spdxlicense/generate/license.go (hunk 2 above)
Comment (kzantow) [reply internal/spdxlicense/generate/license.go:63]: Thanks for the look @spiffcs -- this function is `canReplace`, I think we haven't seen this bug because the other negative test conditions failed first. Basically: this function is trying to find any license that could be replaced by another license by checking equality in almost all the other fields. However, when it gets to the end here, the condition previously here is "if the ID is _NOT_ the same, we can consider it equal". Two comments about this: 1) this is not ever triggered based on the current document, and 2) I really don't think this is right -- if at the end of all the checks, the IDs are the same, it would return `false`... which means _maybe_ we have different `Text`...

File: internal/spdxlicense/generate/generate_license_list_test.go (hunk 1 above)
Comment (kzantow) [reply internal/spdxlicense/generate/generate_license_list_test.go:25]: Yes, I believe  these should be lower cased. I don't see any license with upper case variants.

**Review by spiffcs — APPROVED** [review]

**Comment by vargenau** [comment]
Thank you all for accepting and improving my patch.

I confirm it works as expected for me.

Can you also have a look at at pull request #1259 ? Thank you

**Comment by vargenau** [comment]
Please check also pull request #1266 One more deprecated SPDX license: StandardML-NJ
