### PR TITLE
fix:handle compound aliases like ```.tgz``` when cataloging archives

### LINKED ISSUE #4416: v1.38.0 generates empty sbom for tgz sources
**What happened**:

I used `file:/path/to/my.tgz` as the source for syft to scan.

**What you expected to happen**:

I expected to get an SBOM with data but instead, the SBOM is created but empty (no packages found - no data scanned).

**Steps to reproduce the issue**:

Tar up a filesystem and throw it at syft. We use this yaml with `syft -c`:
```
file:
  metadata:
    selection: all
    digests:
      - sha256

output:
  - spdx-json

format:
    pretty: true

source:
  file:
    digests:
      - sha256

package:
  cataloger:
    scope:
      - squashed
```

**Anything else we need to know?**:

An empty SBOM is not created with `v1.37.0`. That version generates a usable sbom from a tgz. Nothing in the [changelog](https://github.com/anchore/syft/releases/tag/v1.38.0) states this is no longer supported in v1.38.0. The same fs.tgz cannot be used with v1.38.0 but is fine with v1.37.0 and older.

This has kind of broken our build pipeline because we always tell syft to scan the artefact created by the build stage, whether it be a directory or an fs.tgz. Directory scanning is fine (as is `oci-archive:/path/to/oci.tar`) but scanning tar balls is broken.

**Environment**:
- Output of `syft version`:
- OS (e.g: `cat /etc/os-release` or similar):

syft 1.38.0 on Debian Bookworm

### PR DESCRIPTION
**Pull request by VictorHuu**
# Description

see: https://github.com/anchore/syft/issues/4416#issuecomment-3594688303

In the near future, it's the library ```archives``` who should fix the logic to support compound extension names like ```.tgz``` 

- Fixes #4416 

### Summary of magic bytes vs extension for archive detection:
update:
file_source.go:213 - switch to stream-based (already opens file later anyway)
tar_file_traversal.go:23 - opens the file on line 17, so could pass tarReader

defer detection and use new map:
unknowns_tasks.go:64 only has coords.RealPath, would need to open files (potential perf hit for many files)
model.go:159 isArchive() is a helper - opening files could be more expensive here

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] I have added unit tests that cover changed behavior
- [x] I have tested my code in common scenarios and confirmed there are no regressions
- [x] I have added comments to my code, particularly in hard-to-understand sections

### CODE REVIEW

**Comment by spiffcs** [comment]
Wow TY so much @VictorHuu for the PR. I think there are some other sections where we use Identify and want this fix. I'm going to push some changes here and we'll use this branch as the fix.

**Comment by spiffcs** [comment]
I'm also going to quickly explore an approach suggested by @willmurphyscode which would pass the reader. This might give us better automatic detection here where we don't have to implement/maintain this map 😄

**Comment by spiffcs** [comment]
Looks like I need to check the CLI tests now with the new split approach

File: internal/file/archive_aliases.go [hunk 1]
```diff
@@ -0,0 +1,69 @@
...
+		return strings.TrimSuffix(path, ext) + newExt
+	}
+	return path
+}
+
+// HandleCompoundArchiveAliases is the exported version for cases where only
+// path normalization is needed without identification.
+//
+// Deprecated: Prefer using IdentifyArchive which handles aliases automatically.
+func HandleCompoundArchiveAliases(path string) string {
```
Comment (willmurphyscode) [inline internal/file/archive_aliases.go]: Doo we still need this to be exported / exist?

File: internal/file/archive_aliases.go [hunk 2]
```diff
@@ -0,0 +1,69 @@
...
+	".tzst": ".tar.zst",
+}
+
+// IdentifyArchive is a wrapper around archives.Identify that handles compound extension
+// aliases (like .tgz -> .tar.gz) transparently. It first attempts filename-based detection
+// using the alias map, and falls back to content-based detection if needed.
+//
+// This function is a drop-in replacement for archives.Identify that centralizes
+// the compound alias handling logic in one place.
+func IdentifyArchive(ctx context.Context, path string) (archives.Format, io.Reader, error) {
```
Comment (willmurphyscode) [inline internal/file/archive_aliases.go]: Previously, do we ever already have a file open when calling `archives.Identify`? Should this accept a reader rather than trying to open the file?

Comment (spiffcs) [reply internal/file/archive_aliases.go]: I think it's better here if the function handles opening and closing it's own content here. If we pass a reader and it gets used then there might be instances in the code where we expect it to still be available after the function is called and is no longer available. I can check to see if we don't do this, but I thought a more defensive approach would be to create/cleanup its own resources here.

File: internal/file/archive_aliases.go [hunk 3]
```diff
@@ -0,0 +1,69 @@
...
+	// First, try to identify using the alias-mapped path (filename-based detection)
+	normalizedPath := handleCompoundArchiveAliases(path)
+	format, outReader, err := archives.Identify(ctx, normalizedPath, nil)
+	if err == nil && format != nil {
+		return format, outReader, nil
+	}
+
+	// If filename-based detection failed,
+	// try opening the file for content-based detection
+	f, openErr := os.Open(path)
```
Comment (willmurphyscode) [inline internal/file/archive_aliases.go]: I thought that falling back to reading bytes from the file was a behavior change we didn't want?

Also, do we always get here if the file is not an archive? That might be a lot of extra `os.Open` calls if so.

File: internal/file/archive_aliases.go (hunk 1 above)
Comment (spiffcs) [reply internal/file/archive_aliases.go]: removed

File: syft/source/filesource/file_source.go [hunk 4]
```diff
@@ -207,10 +207,16 @@ func fileAnalysisPath(path string, skipExtractArchive bool) (string, func() erro
 		return analysisPath, cleanupFn, nil
 	}
 
-	// if the given file is an archive (as indicated by the file extension and not MIME type) then unarchive it and
+	// if the given file is an archive (as indicated by magic bytes) then unarchive it and
 	// use the contents as the source. Note: this does NOT recursively unarchive contents, only the given path is
 	// unarchived.
-	envelopedUnarchiver, _, err := archives.Identify(context.Background(), path, nil)
+	f, err := os.Open(path)
```
Comment (willmurphyscode) [inline syft/source/filesource/file_source.go]: It looks like here we're open a file so that we can pass it in to `archives.Identify`, but then we don't because our wrapper now only accepts a string. Do we still need to open this?

File: internal/file/archive_aliases.go (hunk 3 above)
Comment (spiffcs) [reply internal/file/archive_aliases.go]: Oh - I might have misunderstood our sync. I thought we wanted to try the easy way `via extension` and have this as a fall through if that failed for any reason.

File: syft/source/filesource/file_source.go (hunk 4 above)
Comment (spiffcs) [reply syft/source/filesource/file_source.go]: yep this can be removed now - missed pulling it out when centralizing everything

File: internal/file/archive_aliases.go (hunk 2 above)
Comment (willmurphyscode) [reply internal/file/archive_aliases.go]: See [comment below](https://github.com/anchore/syft/pull/4421/files#r2582805430) - I thought we had discussed that actually reading bytes from the file to check whether its an archive was a behavior change we didn't necessarily want in this bugfix release. 

I don't think it's correct to `os.Open` here, but I'm not clear on when we reach line 42.

**Comment by spiffcs** [comment]
TY @VictorHuu for the help on this one
