### PR TITLE
fix:allow golang tip image detection regex pattern

### LINKED ISSUE #3681: Support golang tip image
**What would you like to be added**:

Support golang tip image in binary detection

**Additional context**:

```
$ syft -q golang:tip | grep ^go
$ docker run -it --rm golang which go
/usr/local/go/bin/go
$ docker run -it --rm golang:tip go version
go version devel go1.25-d524e1e Sun Feb 16 07:23:13 2025 -0800 linux/amd64
$ docker run -it --rm golang:tip strings /usr/local/go/bin/go | grep -e '1\.25'
devel go1.25-d524e1e Sun Feb 16 07:23:13 2025 -0800
3devel go1.25-d524e1e Sun Feb 16 07:23:13 2025 -0800
```

### PR DESCRIPTION
**Pull request by VictorHuu**
# Description
This PR fixes an issue with the binary classifier for go-binary-hint, which currently fails to detect development version like ```go1.25-d524e1e``` under ```bin/go``` not ```VERSION``` file.

The fix adds a new classifier ```go-binary-hint-dev``` to accommodate the unreleased golang images since the ```FileGlob``` only support one pattern and updates the regex to make it compatible with the tip images.

Now, it works :
```bash
$ syft -q golang:tip | grep ^go
go                         1.25-38d146d                    binary
```
Fixed  #3681

## Type of change
 Bug fix (non-breaking change which fixes an issue)
# Checklist:
- [x] I have added unit tests that cover changed behavior
- [x]  I have tested my code in common scenarios and confirmed there are no regressions
- [x] I have added comments to my code, particularly in hard-to-understand sections

### CODE REVIEW

File: syft/pkg/cataloger/binary/classifiers.go [hunk 1]
```diff
@@ -173,7 +173,16 @@ func DefaultClassifiers() []Classifier {
...
 			EvidenceMatcher: FileContentsVersionMatcher(
-				`(?m)go(?P<version>[0-9]+\.[0-9]+(\.[0-9]+|beta[0-9]+|alpha[0-9]+|rc[0-9]+)?)`),
+				`(?m)go(?P<version>[0-9]+\.[0-9]+(\.[0-9]+|beta[0-9]+|alpha[0-9]+|rc[0-9]+)?)(-[0-9a-f]{7})?`),
+			Package: "go",
+			PURL:    mustPURL("pkg:generic/go@version"),
+			CPEs:    singleCPE("cpe:2.3:a:golang:go:*:*:*:*:*:*:*:*", cpe.NVDDictionaryLookupSource),
+		},
+		{
+			Class:    "go-binary-hint-dev",
+			FileGlob: "**/go",
```
Comment (kzantow) [inline syft/pkg/cataloger/binary/classifiers.go:183]: There is an existing `**/go` matcher: https://github.com/anchore/syft/blob/0fb4cb6d4fd71b59a71b66e15e10900272430ea1/syft/pkg/cataloger/binary/classifiers.go#L49-L57 -- rather than adding a new one, this should be updated.

Comment (VictorHuu) [reply syft/pkg/cataloger/binary/classifiers.go:183]: Thanks for your review! I've found that ```**/VERSION*``` is more universal ,because the version of tip images can only be found at ```zbootstrap.go``` and ```VERSION.cache``` ,and the pattern of the latter are more compatible.
The reason why the ```**/go``` won't be adopted is that it's too unspecific and costly since the go binary is too huge to scan.
```bash
docker run -it --rm golang:tip grep -r "go1.25-38d146d" /usr/local/go/
/usr/local/go/src/internal/buildcfg/zbootstrap.go:const version = `devel go1.25-38d146d Sun Mar 16 15:46:25 2025 -0700`
/usr/local/go/VERSION.cache:devel go1.25-38d146d Sun Mar 16 15:46:25 2025 -0700
```

File: syft/pkg/cataloger/binary/test-fixtures/classifiers/snippets/go-version-hint-dev/1.25/any/go [hunk 2]
```diff
@@ -0,0 +1,2 @@
+devel go1.25-d524e1e Sun Feb 16 07:23:13 2025 -0800
+3devel go1.25-d524e1e Sun Feb 16 07:23:13 2025 -0800
```
[the remark this answers is not in the document]
Comment (VictorHuu) [reply syft/pkg/cataloger/binary/test-fixtures/classifiers/snippets/go-version-hint-dev/1.25/any/go:2]: the go binary, since there's no ```VERSION``` in the tip images

**Review by wagoodman — APPROVED** [review]
