### PR TITLE
fix: fetch Dart package versions from sdk entries

### LINKED ISSUE #3158: Dart: Syft incorrectly generates SBOM with version 0.0.0 for SDK dependencies
**What happened**:

Trivy tool had the same issue which was [raised here](https://github.com/aquasecurity/trivy/discussions/5984).

We are using syft to generate SBOMs for our Dart/Flutter project.
Syft incorrectly generates a dependency for flutter@0.0.0, ignoring the sdk setting.

Corresponding part of the pubspec.lock:

```yaml
…
flutter:
    dependency: "direct main"
    description: flutter
    source: sdk
    version: "0.0.0"
…
```

As you can see it specifies source as sdk.

Further down in the pubspec.lock file there is more information on the sdk version:

```yaml
sdks:
  dart: ">=2.15.1 <3.0.0"
  flutter: ">=2.8.0"

```
**What you expected to happen**:

The generated SBOM should not contain the incorrect (but unfortunately valid) version 0.0.0.

**Steps to reproduce the issue**:

Our project code is private, but the problem exists in any Flutter project.

You can reproduce the problem easily by running `syft scan dir:./ -o spdx-json=sbom.spdx.json` on this project: 

https://github.com/KhoaSuperman/findseat/

**Anything else we need to know?**:

One more thing, **dart** ain't been added to the SBOM either. So it is not only flutter that fails due to the actuall version been in the `sdks` zone but also dart is not being captured.

**Environment**:
- Output of `syft version`: 1.11.1
- OS (e.g: `cat /etc/os-release` or similar): Sonoma 14.1

### PR DESCRIPTION
**Pull request by sgreg**
# Description

Packages that are provided by an SDK, mainly Flutter, will have their version set to 0.0.0 in Dart's pubspec.lock file. Their actual version is linked to that SDK, which is defined either as a version range or a minimum supported version, rather than an explicit, single version.

The pubspec.lock file has a dedicated section to define those SDK version range constraints, which is already stored internally when parsing the file itself. The solution now is to look up such a package's SDK name, retrieve the defined version range / lower version boundary, and set the minimum supported version as the package's new version.

- Fixes #3158 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] I have added unit tests that cover changed behavior
- [x] I have tested my code in common scenarios and confirmed there are no regressions
- [x] I have added comments to my code, particularly in hard-to-understand sections

### CODE REVIEW

File: syft/pkg/cataloger/dart/parse_pubspec_lock.go [hunk 1]
```diff
@@ -68,8 +70,28 @@ func parsePubspecLock(_ context.Context, _ file.Resolver, _ *generic.Environment
...
+			// should refer to the SDK version, which is defined in a dedicated section
+			// in the pubspec.lock file and uses a version range constraint.
+			//
+			// If such a package is detected, look up the version range constraint of
+			// its matching SDK, and set the minimum supported version as its new version.
+			sdkName := pkg.Description.Name
+			sdkVersion, err := p.getSdkVersion(sdkName)
+
+			if err != nil {
+				log.Infof("Failed to resolve %s SDK version for package %s: %v", sdkName, name, err)
```
Comment (wagoodman) [inline syft/pkg/cataloger/dart/parse_pubspec_lock.go:88]:
```suggestion
				log.Tracef("failed to resolve %s SDK version for package %s: %v", sdkName, name, err)
```

File: syft/pkg/cataloger/dart/parse_pubspec_lock.go [hunk 2]
```diff
@@ -68,8 +70,28 @@ func parsePubspecLock(_ context.Context, _ file.Resolver, _ *generic.Environment
...
+			} else {
+				log.Debugf("Resolved %s SDK version for package %s to %s", sdkName, name, sdkVersion)
```
Comment (wagoodman) [inline syft/pkg/cataloger/dart/parse_pubspec_lock.go:90]:
```suggestion
				log.Tracef("resolved %s SDK version for package %s to %s", sdkName, name, sdkVersion)
```

File: syft/pkg/cataloger/dart/parse_pubspec_lock.go [hunk 3]
```diff
@@ -68,8 +70,28 @@ func parsePubspecLock(_ context.Context, _ file.Resolver, _ *generic.Environment
...
+			// version set to "0.0.0" in the package definition. The actual version
+			// should refer to the SDK version, which is defined in a dedicated section
+			// in the pubspec.lock file and uses a version range constraint.
+			//
+			// If such a package is detected, look up the version range constraint of
+			// its matching SDK, and set the minimum supported version as its new version.
+			sdkName := pkg.Description.Name
+			sdkVersion, err := p.getSdkVersion(sdkName)
+
+			if err != nil {
```
Comment (wagoodman) [inline syft/pkg/cataloger/dart/parse_pubspec_lock.go:87]: if we run into an error, I think we should clear the version from the package entirely (since 0.0.0 is not correct). This would allow the package name/version compliance policy to be correctly applied.

File: syft/pkg/cataloger/dart/parse_pubspec_lock.go [hunk 4]
```diff
@@ -89,6 +111,68 @@ func parsePubspecLock(_ context.Context, _ file.Resolver, _ *generic.Environment
...
+//	getSdkVersion("flutter") -> "3.24.5"
+//	getSdkVersion("undefined") -> error
+func (psl *pubspecLock) getSdkVersion(sdk string) (string, error) {
+	constraint, found := psl.Sdks[sdk]
+
+	if !found {
+		return "", fmt.Errorf("cannot find %s SDK", sdk)
+	}
+
+	return parseMinimumSdkVersion(constraint)
```
Comment (wagoodman) [inline syft/pkg/cataloger/dart/parse_pubspec_lock.go:137]: the python cataloger does similar behavior for requirements.txt parsing (when a range is found). In that case we have a configuration item for the cataloger. Just mentioning from a consistency perspective, but ultimately I think that a config item probably is not needed in this case.

File: syft/pkg/cataloger/dart/parse_pubspec_lock.go (hunk 3 above)
Comment (sgreg) [reply syft/pkg/cataloger/dart/parse_pubspec_lock.go:85]: Hope you understood you correct with this: if resolving the version fails, the package itself is now skipped and not added to the package list.

File: syft/pkg/cataloger/dart/parse_pubspec_lock.go (hunk 4 above)
Comment (sgreg) [reply syft/pkg/cataloger/dart/parse_pubspec_lock.go:139]: I think the case is a bit different with Dart here.

As far as I can tell, `pubspec.lock` always lists exact versions for the packages (`pubspec.yaml` would be a different situation), only the SDK section in it uses ranges / minimum version. Making the version guessing a config option would potentially mean that anything related to the Flutter SDK, including Flutter itself, might be omitted from the SBOM. Not sure if that's a good idea :)

**Comment by derbauer97** [comment]
Hello,

We are very interested in the fix you have proposed as it will benefit our users. Could you please let us know when you plan to release it? We already tested it against one of our applications and the flutter version is now recognized correctly :)

**Comment by dariozachow** [comment]
any updates on this pr?

**Comment by sgreg** [comment]
@wagoodman just checking, is there anything you'd still need me to do here? Or is this simply waiting for your internal review process? Just making sure I didn't miss something and block my own PR here :)
