### PR TITLE
fix: add BOMRef to CycloneDX OS Component

### LINKED ISSUE #2101: CycloneDX OS component does not have a bom-ref
**What happened**:
Running `syft ubuntu:latest -o cyclonedx-json` includes a component representing the operating system, but it does not include a `bom-ref`:

```json
    {
      "type": "operating-system",
      "name": "ubuntu",
      "version": "22.04",
      "description": "Ubuntu 22.04.3 LTS",
      "swid": {
        "tagId": "ubuntu", 
        "name": "ubuntu",
        "version": "22.04"
      },
      "externalReferences": [
        { 
          "url": "https://bugs.launchpad.net/ubuntu/",
          "type": "issue-tracker"
        },
        {
          "url": "https://www.ubuntu.com/",
          "type": "website"
        },
        {
          "url": "https://help.ubuntu.com/",
          "comment": "support",
          "type": "other"
        },
        {
          "url": "https://www.ubuntu.com/legal/terms-and-policies/privacy-policy",
          "comment": "privacyPolicy",
          "type": "other"
        }
      ],
      "properties": [
        {
          "name": "syft:distro:id",
          "value": "ubuntu"
        },
        {
          "name": "syft:distro:idLike:0",
          "value": "debian"
        },
        {
          "name": "syft:distro:prettyName",
          "value": "Ubuntu 22.04.3 LTS"
        },
        {
          "name": "syft:distro:versionCodename",
          "value": "jammy"
        },
        {
          "name": "syft:distro:versionID",
          "value": "22.04"
        }
      ]
    }
```

**What you expected to happen**:
A `bom-ref` is set for the component.

**Steps to reproduce the issue**:
`syft ubuntu:latest -o cyclonedx-json`

**Anything else we need to know?**:

**Environment**:
- Output of `syft version`:
Application:     syft
Version:         0.89.0
BuildDate:       2023-08-31T14:50:32Z
GitCommit:       Homebrew
GitDescription:  [not provided]
Platform:        darwin/amd64
GoVersion:       go1.21.0
Compiler:        gc

### PR DESCRIPTION
**Pull request by kzantow**
This PR adds a `BOMRef` to the output CycloneDX OS Component.

Fixes #2101

### CODE REVIEW

File: syft/format/common/cyclonedxhelpers/to_format_model.go [hunk 1]
```diff
@@ -82,10 +83,12 @@ func toOSComponent(distro *linux.Release) []cyclonedx.Component {
 	if len(props) > 0 {
 		properties = &props
 	}
+	bomRef := fmt.Sprintf("os:%s@%s", distro.ID, distro.VersionID)
```
Comment (wagoodman) [inline syft/format/common/cyclonedxhelpers/to_format_model.go:86]: I think we should check for cases when the ID or VersionID is missing -- I think I've seen this before, trying to collect some examples

Comment (wagoodman) [reply syft/format/common/cyclonedxhelpers/to_format_model.go:86]: arch linux is an example of a missing version
```
docker run --rm -it --platform linux/amd64 archlinux:latest
[root@92ced9395309 /]# cat /etc/os-release
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
VERSION_ID=20240101.0.204074
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo
```

Comment (kzantow) [reply syft/format/common/cyclonedxhelpers/to_format_model.go:86]: If these are empty values, we would get something like: `os:@1.23`, `os:thing@` or `os:@`. These are all fairly clear to me that a name and/or version is missing and should be unique within the document, is there some other behavior that you'd expect?

Comment (wagoodman) [reply syft/format/common/cyclonedxhelpers/to_format_model.go:86]: Small changes like `os:unknown` over `os:@1.23` or `os:@` and `os:thing` over `os:thing@`. I was originally thinking looking at fallback fields such as ID_LIKE, PRETTY_NAME, NAME, VERSION, etc... but I don't think that would be a good idea yet since some of these fields might give an incorrect indication of the identity (like ID_LIKE).

Comment (kzantow) [reply syft/format/common/cyclonedxhelpers/to_format_model.go]: I don't have a strong opinion on the verbiage; added some hopefully obviuous/clear things; test that show what it looks like are: https://github.com/anchore/syft/pull/2634/files#diff-ef679fb96ee08c5fcd0fe9323424af7502f51d170aa8571f861632027749ef0cR292-R315

**Review by wagoodman — APPROVED** [review]
not a huge fan of the naming in unknown conditions, but can't argue with it's clarity... 👍
