### PR TITLE
fix: allow template for syft convert

### LINKED ISSUE #1409: Multiple output files with templates
### Description
When running syft with multiple -o=template  -t=templateFile  parameters it takes the latest templateFile for every output file

### Example
Input syft alpine -o template=f1.json -t f1.template -o template=f2.json -t f2.template 
Output:
- f1.json with f2.template
- f2.json with f2.template

### PR DESCRIPTION
**Pull request by kzantow**
This PR corrects an issue where `syft convert <sbom> -o template --template <file>` was not working.

Fixes #1409

### CODE REVIEW

File: test/cli/all_formats_convertible_test.go [hunk 1]
```diff
@@ -26,52 +22,48 @@ func TestConvertCmdFlags(t *testing.T) {
...
-				{To: "spdx-json", From: "cyclonedx-json"},
-				{To: "cyclonedx-json", From: "syft-json"},
-				{To: "cyclonedx-json", From: "spdx-json"},
-			},
-			assertions: commonAssertions,
-		},
+		{to: "syft-json", from: "spdx-json"},
+		{to: "syft-json", from: "cyclonedx-json"},
+		{to: "spdx-json", from: "syft-json"},
+		{to: "template", from: "syft-json", template: "test-fixtures/csv.template"},
```
Comment (wagoodman) [inline test/cli/all_formats_convertible_test.go:33]: ❤️

**Review by wagoodman — APPROVED** [review]
