### PR TITLE
fix: nondeterministic Java archive cataloging and improve groupID

### LINKED ISSUE #3521: PURL is not deterministic in java-archive cataloger
**What happened**:
When i scan a file (.war) I get different results each scan. A jar with multiple `pom.xml` can result in, for example:
```
pkg:maven/org.glassfish.jaxb/jaxb-core@2.2.11
pkg:maven/com.sun.xml.bind/jaxb-core@2.2.11
```

**What you expected to happen**:
same result each time

**Steps to reproduce the issue**:
Repeatedly scan `webgoat/webgoat` [container](https://hub.docker.com/r/webgoat/webgoat) or JAR [releases](https://github.com/WebGoat/WebGoat/releases)

**Anything else we need to know?**:
it impacts the number of results I get from syft.

**Environment**:
- Output of `syft version`: 1.17.0
- OS (e.g: `cat /etc/os-release` or similar): mac

### PR DESCRIPTION
**Pull request by kzantow**
# Description

This PR fixes an issue where the Java archive cataloger could select the groupID in a nondeterministic fashion, resulting in different SBOMs on the same source material. Additionally, the logic to select the groupID and artifactID combination for Maven artifacts did not take into account the potential inclusion of groupID in the filename. As noted in the comment, this PR adjusts the behavior to be what I think is more correct when determining which pom the artifact represents: it will now favor POMs where both groupID and artifactID match, followed by exact match of the filename, and so on.

- Fixes #3521

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] I have added unit tests that cover changed behavior
- [x] I have tested my code in common scenarios and confirmed there are no regressions
- [x] I have added comments to my code, particularly in hard-to-understand sections

### CODE REVIEW

File: syft/pkg/cataloger/java/archive_parser.go [hunk 1]
```diff
@@ -391,20 +394,32 @@ func (j *archiveParser) discoverMainPackageFromPomInfo(ctx context.Context) (gro
 	projects, _ := pomProjectByParentPath(j.archivePath, j.location, j.fileManifest.GlobMatch(false, pomXMLGlob))
 
 	// map of all the artifacts in the pom properties, in order to chek exact match with the filename
-	artifactsMap := make(map[string]bool)
+	artifactsMap := strset.New()
```
Comment (kzantow) [inline syft/pkg/cataloger/java/archive_parser.go:397]: This is just for memory optimization.

File: syft/pkg/cataloger/java/archive_parser.go [hunk 2]
```diff
@@ -784,3 +800,15 @@ func updateParentPackage(p pkg.Package, parentPkg *pkg.Package) {
 		parentPkg.Metadata = parentMetadata
 	}
 }
+
```
Comment (ariel-miculas) [inline syft/pkg/cataloger/java/archive_parser.go:803]: I think a [BTreeMap](https://pkg.go.dev/github.com/tidwall/btree#Map) would remove the need for this sortedIter.

Comment (kzantow) [reply syft/pkg/cataloger/java/archive_parser.go:803]: This is a good suggestion, but would require adding yet another library and reworking all the parts here using maps, which I'd like to avoid just for this small bugfix.

**Review by spiffcs — APPROVED** [review]
