### PR TITLE
fix: update graalvm cataloger to fix panic

### LINKED ISSUE #1453: syft is now throwing panic with version 0.66.0
**Please provide a set of steps on how to reproduce the issue**

Run syft version 0.66.0 against an image in DockerHub now produces an error.

syft packages registry:xxxxx/xxxx:xxxxx --scope squashed -o table -v 

**What happened**:

panic: interface conversion: interface {} is *pe.OptionalHeader32, not *pe.OptionalHeader64

goroutine 243 [running]:
github.com/anchore/syft/syft/pkg/cataloger/java.newPE({0xc001c9bb00, 0x3c}, {0x7f4b44402c68, 0xc04d772de0?})
	/home/runner/work/syft/syft/syft/pkg/cataloger/java/graalvm_native_image_cataloger.go:234 +0x4e9
github.com/anchore/syft/syft/pkg/cataloger/java.fetchPkgs({0x7f4b44402c30?, 0xc04d772de0?}, {0xc001c9bb00, 0x3c})
	/home/runner/work/syft/syft/syft/pkg/cataloger/java/graalvm_native_image_cataloger.go:510 +0x219
github.com/anchore/syft/syft/pkg/cataloger/java.(*NativeImageCataloger).Catalog(0xc00007e360?, {0x145dd68, 0xc0077d80c8})
	/home/runner/work/syft/syft/syft/pkg/cataloger/java/graalvm_native_image_cataloger.go:544 +0x4e5
github.com/anchore/syft/syft/pkg/cataloger.runCataloger({0x1456150, 0x1d55e10}, {0x145dd68?, 0xc0077d80c8})
	/home/runner/work/syft/syft/syft/pkg/cataloger/catalog.go:57 +0x188
github.com/anchore/syft/syft/pkg/cataloger.Catalog.func1()
	/home/runner/work/syft/syft/syft/pkg/cataloger/catalog.go:127 +0x105
created by github.com/anchore/syft/syft/pkg/cataloger.Catalog
	/home/runner/work/syft/syft/syft/pkg/cataloger/catalog.go:122 +0x2aa

**What you expected to happen**:

Scan should proceed with results produced.

**Anything else we need to know?**:

**Environment**:
- Output of `syft version`: 0.66.0
- OS (e.g: `cat /etc/os-release` or similar): 22.04.1 LTS (Jammy Jellyfish)

### PR DESCRIPTION
**Pull request by kzantow**
This PR corrects a panic in the graalvm cataloger due to differences in 32/64-bit binaries.

Fixes #1453

### CODE REVIEW

File: syft/pkg/cataloger/java/graalvm_native_image_cataloger.go [hunk 1]
```diff
@@ -231,8 +231,13 @@ func newPE(filename string, r io.ReaderAt) (nativeImage, error) {
 	if err != nil {
 		return fileError(filename, err)
 	}
-	optionalHeader := bi.OptionalHeader.(*pe.OptionalHeader64)
-	exportSymbolsDataDirectory := optionalHeader.DataDirectory[0]
+	var exportSymbolsDataDirectory pe.DataDirectory
+	switch h := bi.OptionalHeader.(type) {
```
Comment (wagoodman) [inline syft/pkg/cataloger/java/graalvm_native_image_cataloger.go:235]: there should be a default case that gracefully returns an error too

**Review by spiffcs — APPROVED** [review]
