### PR TITLE
Find version numbers from jars with different naming conventions

### LINKED ISSUE #466: Java-Cataloger produces empty entries for cyclonedx output
**What happened**:

Scanning a docker image with a Java WAR-Artifact produces empty entries in cyclonedx output format:

```xml
<components>
    <component type="library">
      <name></name>
      <version></version>
    </component>
    <component type="library">
      <name></name>
      <version></version>
</component>
```
The json output looks like

```yaml
{
   "id": "a61fa28f-5d6b-4278-9ca7-d1edc7e00e70",
   "name": "",
   "version": "",
   "type": "java-archive",
   "foundBy": "java-cataloger",
   "locations": [
    {
     "path": "/opt/app/tomcat/webapps/app.war",
     "layerID": "sha256:5f55e12fb870a80ebd203ebbaa56276a728e382373f3b76a243d2fd3ff17cb29"
    }
   ],
   "licenses": [],
   "language": "java",
   "cpes": [
    "cpe:2.3:a:*:*:*:*:*:*:*:java:*:*",
    "cpe:2.3:a:*:*:*:*:*:*:*:maven:*:*",
    "cpe:2.3:a:*:*:*:*:*:*:*:*:*:*"
   ],
   "purl": "",
   "metadataType": "JavaMetadata",
   "metadata": {
    "virtualPath": "/opt/app/tomcat/webapps/app.war:WEB-INF/lib/xalan/xml-apis.1.3.04.jar",
    "manifest": {
     "main": {
      "Ant-Version": "Apache Ant 1.6.5",
      "Created-By": "1.3.1 (IBM Corporation)",
      "Manifest-Version": "1.0"
     },
```
We use the cyclonedx format to export the BOM to dependency-track but the BOM import fails due to the missing name:

`ERROR:  null value in column "NAME" violates not-null constraint`

According to the [cyclonedx-spec](https://cyclonedx.org/docs/1.2/#type_component) name is a required attribute and an empty attribute does not make sense if it's required.

**What you expected to happen**:

Strip empty entries from the cyclonedx output or insert something like _unknow component_ or just the filename.

**How to reproduce it (as minimally and precisely as possible)**:

Download [xml-apis-1.3.04](https://repo1.maven.org/maven2/xml-apis/xml-apis/1.3.04/xml-apis-1.3.04.jar) from maven and use the docker command to scan the dir with the artifact:

`docker run -v /opt/test/:/work -w /work anchore/syft:latest ./ -o json`

**Anything else we need to know?**:

- none

**Environment**:

docker image `anchore/syft:latest`

> Application:   syft
> Version:       0.19.1
> BuildDate:     2021-06-30T17:32:06Z
> GitCommit:     fee35dd1753308fc887da744de5d0c66947c7493
> GitTreeState:  clean
> Platform:      linux/amd64
> GoVersion:     go1.16.5
> Compiler:      gc

### PR DESCRIPTION
**Pull request by kzantow**
This PR adds support for different JAR naming conventions -- specifically `<name>.<version>` and `<name>_<version>`.

Closes #466

### CODE REVIEW

File: syft/pkg/cataloger/java/archive_filename.go [hunk 1]
```diff
@@ -48,7 +48,8 @@ import (
 //	my-http2-server-5		-->	name="my-http2-server", version="5"
 //	jetpack-build235-rc5	-->	name="jetpack", version="build2.0-rc5"
 //	ironman-r4-2009			--> name="ironman", version="r4-2009"
-var nameAndVersionPattern = regexp.MustCompile(`(?Ui)^(?P<name>(?:[[:alpha:]][[:word:].]*(?:\.[[:alpha:]][[:word:].]*)*-?)+)(?:-(?P<version>(?:\d.*|(?:build\d*.*)|(?:rc?\d+(?:^[[:alpha:]].*)?))))?$`)
+var nameAndVersionPattern = regexp.MustCompile(`(?Ui)^(?P<name>(?:[[:alpha:]][[:word:].]*(?:\.[[:alpha:]][[:word:].]*)*-?)+)(?:-(?P<version>(\d.*|(build\d*.*)|(rc?\d+(?:^[[:alpha:]].*)?))))?$`)
```
Comment (kzantow) [inline syft/pkg/cataloger/java/archive_filename.go:51]: NOTE: this gets rid of warnings for ignored capture groups `(?:`, which were already ignored.

File: syft/pkg/cataloger/java/archive_filename.go [hunk 2]
```diff
@@ -48,7 +48,8 @@ import (
...
+var secondaryVersionPattern = regexp.MustCompile(`(?:[._-](?P<version>(\d.*|(build\d*.*)|(rc?\d+(?:^[[:alpha:]].*)?))))?$`)
```
Comment (kzantow) [inline syft/pkg/cataloger/java/archive_filename.go:52]: Implemented as a secondary match due to difficulty making a reasonable regex that would support these alternate jar conventions AND ones like `jboss-saaj-api_1.4_spec-1.0.2.Final.jar`

**Review by spiffcs — APPROVED** [review]
