### PR TITLE
fix: stabilize cpe sorting during collection sort

### LINKED ISSUE #2967: Order CPEs deterministically for SBOM reproducibility
**What happened**:

I'm seeing nondeterministic behavior when using Syft as a library (in wolfictl) to generate SBOMs. I noticed this via new golden-file style tests we've introduced, to ensure we get the same output for the same input. For a couple of the test targets (which are each APK files), a test will fail on the next run immediately following that test's golden file update.

**I'm not 100% sure this is Syft's fault yet**, since there's wrapping code in wolfictl involved, too. But wanted to flag the issue here at least so we can discuss!

Here are some example diffs from two consecutive runs of the [SBOM generation code](https://github.com/wolfi-dev/wolfictl/blob/dc84d81b0556e732b9f8991406b37d017a4c61aa/pkg/sbom/sbom.go#L33) under [this test](https://github.com/wolfi-dev/wolfictl/blob/dc84d81b0556e732b9f8991406b37d017a4c61aa/pkg/sbom/sbom_test.go#L25):

### For `jenkins-2.461-r0.apk`

```diff
 "language": "java",
 "cpes": [
   {
-    "cpe": "cpe:2.3:a:jenkins:mailer:472.vf7c289a_4b_420:*:*:*:*:jenkins:*:*",
-    "source": "nvd-cpe-dictionary"
-  },
-  {
-    "cpe": "cpe:2.3:a:jenkins:mailer:472.vf7c289a_4b_420:*:*:*:*:*:*:*",
+    "cpe": "cpe:2.3:a:jenkins:mailer:472.vf7c289a_4b_420:*:*:*:*:*:*:*",
+    "source": "nvd-cpe-dictionary"
+  },
+  {
+    "cpe": "cpe:2.3:a:jenkins:mailer:472.vf7c289a_4b_420:*:*:*:*:jenkins:*:*",
     "source": "nvd-cpe-dictionary"
```

### For `jruby-9.4-9.4.7.0-r0.apk`:

```diff
 {
-"id": "b18c20e1cb65977c",
+"id": "1ac1bd89c6841000",
 "name": "jruby-base",
 "version": "9.4.7.0",
 "type": "java-archive",
 ...
     }
   }
 ],
-"licenses": [],
+"licenses": [
+  {
+    "value": "Apache-2.0",
+    "spdxExpression": "Apache-2.0",
+    "type": "concluded",
+    "urls": [],
+    "locations": [
+      {
+        "path": "usr/share/jruby/lib/jruby.jar",
+        "accessPath": "usr/share/jruby/lib/jruby.jar",
+        "annotations": {
+          "evidence": "primary"
+        }
+      }
+    ]
+  }
+],
```

**What you expected to happen**:

Same exact output given same input!

**Steps to reproduce the issue**:

Check out https://github.com/wolfi-dev/wolfictl and run the test linked above. Note that you may have to run the test multiple times in order to get a complete sense of the results that code can produce. Also note that the first run of the test is doing a fetch of several APKs, so it will take considerably more time than subsequent test runs.

**Anything else we need to know?**:

So far the only test cases exhibiting this behavior are Java-based packages... 🤔 

cc: @wagoodman, this is the thing we talked about briefly last week.

**Environment**:
- Output of `syft version`:

```console
$ go list -m all | grep syft           
github.com/anchore/syft v1.7.0
```

- OS (e.g: `cat /etc/os-release` or similar): latest macOS

### PR DESCRIPTION
**Pull request by spiffcs**
## Summary
This is not yet fully deterministic but is a branch that attempts to fix #2967 

### Reproduce
```
FROM alpine:latest

RUN apk update

RUN apk add jenkins
```

Build the above image and run syft using this branch
```
for i in (seq 1 20); ~/go/bin/syft -o json 2967:test | jq . > test_sbom/test_$i.json; end
```

Then you can use something like the following to show the sha for each sbom
```
#!/opt/homebrew/bin/fish

# Change directory to the target directory
cd test_sbom

# Loop through each file in the directory
for file in *
    if test -f $file  # Check if the item is a regular file
        set sha (sha256sum $file)
        echo "$sha\t$file"
    end
end
```

On main this produces about 7/8 unique sha for 20 sbom generated against the same image.
On this branch there are only 2 unique sha for the same test.

This is currently WIP to determine what the final non determinism that is causing the two different sha.

### Current determinism progress between main and this branch for the sample image
The final diff for this branch no longer is related to CPE inconsistency and instead exists within how java packages are created and stored in the collection during cataloging. There is also an inconsistency in relationships being generated for the two outputs of `4d076f84e08b338743ee76f68f2ba516267d954dece28ff700c6ebc152ca95a4` and `5d5655ad32cdbfbcdaaabe6a314f6656145ad33dcb54428802fd3dc153e436d0`.

This is what I'm currently investigating before submitting this PR for review.

#### Main
```
7275bc491df371ae43338df29d8bcc91277a949c00dc5aa0b017009ac5442384  test_1.json\ttest_1.json
7275bc491df371ae43338df29d8bcc91277a949c00dc5aa0b017009ac5442384  test_2.json\ttest_2.json
7275bc491df371ae43338df29d8bcc91277a949c00dc5aa0b017009ac5442384  test_3.json\ttest_3.json
7275bc491df371ae43338df29d8bcc91277a949c00dc5aa0b017009ac5442384  test_4.json\ttest_4.json
7275bc491df371ae43338df29d8bcc91277a949c00dc5aa0b017009ac5442384  test_5.json\ttest_5.json
825e8612d1bb070e42451718cab9f69e0439be3228880d697d140f19340ff55a  test_6.json\ttest_6.json
711c903cf104e84ed89b1057f634a4cc594edee6c2007eeb3e489ebb089daf0d  test_7.json\ttest_7.json
7275bc491df371ae43338df29d8bcc91277a949c00dc5aa0b017009ac5442384  test_8.json\ttest_8.json
521a382fb033df30649eb9204519e4bb66d376b353ae11c4a492f2245fb00663  test_9.json\ttest_9.json
2dc6d6f47a53e12c384ea37a6d395461f19ee1a016e8e97b7137330206293406  test_10.json\ttest_10.json
9f86203a5511a109d97f9972fcd79b07ff77b3331058b6016ba5fa1b9ace3b48  test_11.json\ttest_11.json
7275bc491df371ae43338df29d8bcc91277a949c00dc5aa0b017009ac5442384  test_12.json\ttest_12.json
fd0c866c23b306b8dfdd9e64e1f16808037b3c6c9a1425fd45e5411362340bde  test_13.json\ttest_13.json
6257fd4022d7589cdf981a52b25a2e3e532810548358c09fc8e6ca10f43e9a78  test_14.json\ttest_14.json
7275bc491df371ae43338df29d8bcc91277a949c00dc5aa0b017009ac5442384  test_15.json\ttest_15.json
7275bc491df371ae43338df29d8bcc91277a949c00dc5aa0b017009ac5442384  test_16.json\ttest_16.json
297748476a36259f1ff14f6087333823dca77c4f13ce33198acaabbafde254f6  test_17.json\ttest_17.json
9cb06d031e5b6b95279ef0c6a5faf4380acfcc117fb6699ab9c7ea5df7e6095b  test_18.json\ttest_18.json
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  test_19.json\ttest_19.json
```

#### Branch
```
[I] hal@ChristophersMBP ~/d/s/2967> ./sha.fish
4d076f84e08b338743ee76f68f2ba516267d954dece28ff700c6ebc152ca95a4  test_1.json\ttest_1.json
4d076f84e08b338743ee76f68f2ba516267d954dece28ff700c6ebc152ca95a4  test_2.json\ttest_2.json
5d5655ad32cdbfbcdaaabe6a314f6656145ad33dcb54428802fd3dc153e436d0  test_3.json\ttest_3.json
4d076f84e08b338743ee76f68f2ba516267d954dece28ff700c6ebc152ca95a4  test_4.json\ttest_4.json
4d076f84e08b338743ee76f68f2ba516267d954dece28ff700c6ebc152ca95a4  test_5.json\ttest_5.json
4d076f84e08b338743ee76f68f2ba516267d954dece28ff700c6ebc152ca95a4  test_6.json\ttest_6.json
5d5655ad32cdbfbcdaaabe6a314f6656145ad33dcb54428802fd3dc153e436d0  test_7.json\ttest_7.json
4d076f84e08b338743ee76f68f2ba516267d954dece28ff700c6ebc152ca95a4  test_8.json\ttest_8.json
4d076f84e08b338743ee76f68f2ba516267d954dece28ff700c6ebc152ca95a4  test_9.json\ttest_9.json
4d076f84e08b338743ee76f68f2ba516267d954dece28ff700c6ebc152ca95a4  test_10.json\ttest_10.json
5d5655ad32cdbfbcdaaabe6a314f6656145ad33dcb54428802fd3dc153e436d0  test_11.json\ttest_11.json
4d076f84e08b338743ee76f68f2ba516267d954dece28ff700c6ebc152ca95a4  test_12.json\ttest_12.json
4d076f84e08b338743ee76f68f2ba516267d954dece28ff700c6ebc152ca95a4  test_13.json\ttest_13.json
4d076f84e08b338743ee76f68f2ba516267d954dece28ff700c6ebc152ca95a4  test_14.json\ttest_14.json
4d076f84e08b338743ee76f68f2ba516267d954dece28ff700c6ebc152ca95a4  test_15.json\ttest_15.json
4d076f84e08b338743ee76f68f2ba516267d954dece28ff700c6ebc152ca95a4  test_16.json\ttest_16.json
4d076f84e08b338743ee76f68f2ba516267d954dece28ff700c6ebc152ca95a4  test_17.json\ttest_17.json
5d5655ad32cdbfbcdaaabe6a314f6656145ad33dcb54428802fd3dc153e436d0  test_18.json\ttest_18.json
4d076f84e08b338743ee76f68f2ba516267d954dece28ff700c6ebc152ca95a4  test_19.json\ttest_19.json
4d076f84e08b338743ee76f68f2ba516267d954dece28ff700c6ebc152ca95a4  test_20.json\ttest_20.json
```

### CODE REVIEW

**Comment by spiffcs** [comment]
The final bit of nondeterminism here comes from the java cataloger and how packages are deduplicated in the given sample image. I believe on some runs the final `jansi` package is sourced from one of the following virtual path. 

Depending on which "wins" vs the other and makes it into the final SBOM causes other side affects around relationships, cpes, and other metadata regarding the package. 

This causes the sha of the generated SBOM to be different depending on which "jansi" made it into the final document. 

```
-        virtualPath: "/usr/share/webapps/jenkins/jenkins.war:WEB-INF/lib/jansi-1.11.jar:org.fusesource.jansi:jansi"
+        virtualPath: "/usr/share/webapps/jenkins/jenkins.war:WEB-INF/lib/jansi-1.11.jar"
```

In

File: syft/pkg/collection.go [hunk 1]
```diff
@@ -283,6 +285,8 @@ func (c *Collection) Enumerate(types ...Type) <-chan Package {
 // is specified.
 func (c *Collection) Sorted(types ...Type) (pkgs []Package) {
 	for p := range c.Enumerate(types...) {
+		// sort CPE for each package so SBOM have deterministic output
+		sort.Sort(cpe.BySourceThenSpecificity(p.CPEs))
```
Comment (wagoodman) [inline syft/pkg/collection.go:289]: we probably shouldn't be mutating these on read from the collection, but instead at generation of this list. Probably one of these two places:
- https://github.com/anchore/syft/blob/13d01ecaff0aae22f3a5bf6f922a0be4ae7c4d06/syft/pkg/cataloger/internal/cpegenerate/generate.go#L172
- https://github.com/anchore/syft/blob/13d01ecaff0aae22f3a5bf6f922a0be4ae7c4d06/syft/pkg/cataloger/common/cpe/create.go#L10

Comment (spiffcs) [reply syft/pkg/collection.go]: @wagoodman changes made - similar test output showing only two variants that stem from the java cataloger non determinism 
```
./sha.fish
4d076f84e08b338743ee76f68f2ba516267d954dece28ff700c6ebc152ca95a4  test_1.json\ttest_1.json
4d076f84e08b338743ee76f68f2ba516267d954dece28ff700c6ebc152ca95a4  test_2.json\ttest_2.json
4d076f84e08b338743ee76f68f2ba516267d954dece28ff700c6ebc152ca95a4  test_3.json\ttest_3.json
4d076f84e08b338743ee76f68f2ba516267d954dece28ff700c6ebc152ca95a4  test_4.json\ttest_4.json
5d5655ad32cdbfbcdaaabe6a314f6656145ad33dcb54428802fd3dc153e436d0  test_5.json\ttest_5.json
4d076f84e08b338743ee76f68f2ba516267d954dece28ff700c6ebc152ca95a4  test_6.json\ttest_6.json
4d076f84e08b338743ee76f68f2ba516267d954dece28ff700c6ebc152ca95a4  test_7.json\ttest_7.json
4d076f84e08b338743ee76f68f2ba516267d954dece28ff700c6ebc152ca95a4  test_8.json\ttest_8.json
5d5655ad32cdbfbcdaaabe6a314f6656145ad33dcb54428802fd3dc153e436d0  test_9.json\ttest_9.json
4d076f84e08b338743ee76f68f2ba516267d954dece28ff700c6ebc152ca95a4  test_10.json\ttest_10.json
```

**Comment by spiffcs** [comment]
@wagoodman updated based on your comments

**Review by wagoodman — APPROVED** [review]
