### PR TITLE
fixed dotnet-deps cataloger skip project type by def, fixed #4423

### LINKED ISSUE #4423: dotnet-deps cataloger should skip project references with type "project" when building the sbom
**What happened**:

Syft treats project refs from deps.json as if they’re nuget packages in the sbom, even though they’re first-party code, which leads to weird purls like pkg:nuget/myapp@1.0.0

**What you expected to happen**:

by default sbom shouldn't include project references (type: "project") because they're part of the firstparty code

from the .net sdk runtime config spec

"package" is for nuget deps
"project" is for internal refs

I think by default, entries with type "project" must filtered out unless it's the root package, or even add use --include-project-references to include them

**Steps to reproduce the issue**:

**Anything else we need to know?**:

**Environment**:
- Output of `syft version`: latest main
- OS (e.g: `cat /etc/os-release` or similar): all

### PR DESCRIPTION
**Pull request by rezmoss**
# Description

Fixed https://github.com/anchore/syft/issues/4423 

- Fixes #4423 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (please discuss with the team first; Syft is 1.0 software and we won't accept breaking changes without going to 2.0)
- [ ] Documentation (updates the documentation)
- [ ] Chore (improve the developer experience, fix a test flake, etc, without changing the visible behavior of Syft)
- [ ] Performance (make Syft run faster or use less memory, without changing visible behavior much)

# Checklist:

- [x] I have added unit tests that cover changed behavior
- [x] I have tested my code in common scenarios and confirmed there are no regressions
- [ ] I have added comments to my code, particularly in hard-to-understand sections

### CODE REVIEW

File: cmd/syft/internal/options/catalog.go [hunk 1]
```diff
@@ -263,6 +264,9 @@ func (cfg *Catalog) AddFlags(flags clio.FlagSet) {
 
 	flags.StringVarP(&cfg.Source.Supplier, "source-supplier", "",
 		"the organization that supplied the component, which often may be the manufacturer, distributor, or repackager")
+
+	flags.BoolVarP(&cfg.Dotnet.ExcludeProjectReferences, "dotnet-exclude-project-references", "",
+		"exclude packages with type 'project' from deps.json output (default: true)")
```
Comment (kzantow) [inline cmd/syft/internal/options/catalog.go]: We should probably not add a flag for this, it seems like the right behavior to default and override via configuration or environment variable, if needed.

**Comment by kzantow** [comment]
One comment about adding a flag, but also I think you need to regenerate a new schema? After that, this looks good to me 👍

**Review by spiffcs — APPROVED** [review]
