### PR TITLE
3122 valid license url characters

### LINKED ISSUE #3122: Special characters (tab, newline) in license URL
**What happened**:

- We have created a CycloneDX-JSON of our Nexus installation with the last Syft version.
- The UserAgentUtils library version 1.21 is found there as a dependency.
- We have imported this CycloneDX-JSON into the latest version of Dependency-Track.
- There we get the error message:

```
'$.components[9].licenses[0].license.url: does not match the iri-reference pattern must be a valid RFC 3987 IRI-reference'
```

**What you expected to happen**:

The license URL should be without special characters like newlines and tabs in the JSON field url.

**Steps to reproduce the issue**:

1. Download .jar file
https://repo1.maven.org/maven2/eu/bitwalker/UserAgentUtils/1.21/UserAgentUtils-1.21.jar 
2. syft --output cyclonedx-json=file.json --verbose 

**Anything else we need to know?**:

- In the file /META-INF/maven/eu.bitwalker/UserAgentUtils/pom.xml the license field is defined as follows.

```
	<licenses>
		<license>
			<name>New BSD License</name>
			<url>
				http://user-agent-utils.googlecode.com/svn/trunk/UserAgentUtils/LICENSE.txt
			</url>
			<distribution>repo</distribution>
		</license>
	</licenses>
```

- In the CycloneDX-JSON from Syft the license entry is displayed as follows.

```
      "licenses": [
        {
          "license": {
            "name": "New BSD License",
            "url": "\n\t\t\t\thttp://user-agent-utils.googlecode.com/svn/trunk/UserAgentUtils/LICENSE.txt\n\t\t\t"
          }
        }
      ],
```

**Environment**:
- Output of `syft version`:

Application: syft
Version:    1.11.0
BuildDate:  2024-08-09T17:52:25Z
GitCommit:  19cc664cf8e7020dd692a62efcbba98ab670bde9
GitDescription: v1.11.0
Platform:   linux/amd64
GoVersion:  go1.22.5
Compiler:   gc

- OS (`cat /etc/os-release`):

NAME="AlmaLinux"
VERSION="9.4 (Seafoam Ocelot)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.4"
PLATFORM_ID="platform:el9"
PRETTY_NAME="AlmaLinux 9.4 (Seafoam Ocelot)"
ANSI_COLOR="0;34"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:almalinux:almalinux:9::baseos"
HOME_URL="https://almalinux.org/"
DOCUMENTATION_URL="https://wiki.almalinux.org/"
BUG_REPORT_URL="https://bugs.almalinux.org/"

ALMALINUX_MANTISBT_PROJECT="AlmaLinux-9"
ALMALINUX_MANTISBT_PROJECT_VERSION="9.4"
REDHAT_SUPPORT_PRODUCT="AlmaLinux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.4"
SUPPORT_END=2032-06-01

- Dependency-Track

Version: 4.11.6

### PR DESCRIPTION
**Pull request by spiffcs**
# Description

This PR updates the license constructors to strip unwanted characters from URLs in license metadata and make sure all URLs conform to RFC 3987 IRI-reference.

- Fixes #3122

### Fix Validation

- Download .jar file [here](https://repo1.maven.org/maven2/eu/bitwalker/UserAgentUtils/1.21/UserAgentUtils-1.21.jar)
- Run the following command using this branch:
`go run cmd/syft/main.go --output cyclonedx-json=file.json --verbose`

The URL now listed for the `UserAgentUtils` should no longer have special characters in it as listed in the issue.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] I have added unit tests that cover changed behavior
- [x] I have tested my code in common scenarios and confirmed there are no regressions
- [x] I have added comments to my code, particularly in hard-to-understand sections

### CODE REVIEW

File: syft/pkg/license.go [hunk 1]
```diff
@@ -122,13 +129,35 @@ func NewLicenseFromURLs(value string, urls ...string) License {
 	return l
 }
 
+func stripUnwantedCharacters(rawURL string) (string, error) {
+	// Step 1: Remove newline and tab characters
+	cleanedURL := strings.ReplaceAll(rawURL, "\n", "")
+	cleanedURL = strings.ReplaceAll(cleanedURL, "\t", "")
```
Comment (wagoodman) [inline syft/pkg/license.go:135]: the trim space call following this section seem sufficient -- unless we're trying to remove embedded newlines/tabs, but that seems unlikely

File: syft/pkg/license.go [hunk 2]
```diff
@@ -122,13 +129,35 @@ func NewLicenseFromURLs(value string, urls ...string) License {
...
+
+	// Step 2: Trim leading/trailing spaces
+	cleanedURL = strings.TrimSpace(cleanedURL)
+
+	// Step 3: Validate the cleaned URL
+	_, err := url.ParseRequestURI(cleanedURL)
```
Comment (wagoodman) [inline syft/pkg/license.go:141]: should we leave these in the core model but then filter them when encoding sbom specs that have specific requirements? That is, should we move this to the cyclonedx encoder? We could check for any similar requirement for SPDX and do the same.

Comment (spiffcs) [reply syft/pkg/license.go:141]: I think it's best to clean it as early as possible in the process and get our own model's URL inline with the RFC 3987 IRI-reference

**Review by wagoodman — APPROVED** [review]
