### PR TITLE
Fix SPDX namespace value

### LINKED ISSUE #622: SPDX2.2 JSON format should not use UUID random
**What happened**:
When generating an SPDX 2.2 format SBOM, the `documentName` function should not have a `uuid` as the base return case.

https://github.com/anchore/syft/blob/bb0f35bac4e2e610e61be55b27b3810099794479/internal/formats/spdx22json/to_format_model.go#L49-L59

**What you expected to happen**:
I expect the base case name to return a string that is in line with the specification found [here](https://spdx.github.io/spdx-spec/document-creation-information/#64-document-name-field)

### PR DESCRIPTION
**Pull request by wagoodman**
The current SPDX namespace values being produced by syft look like:
```
# note the "https:/" instead of "https://"
https:/anchore.com/syft/...
```

This PR fixes this behavior, moves name and namespace related helpers to the `spdxhelpers` package, and adds assertion around testing to ensure that `source.Scheme`s are fully tested (while writing tests for this it was noticed that cases for `FileScheme` were missing).

Additionally closes #622

### CODE REVIEW

File: internal/formats/common/spdxhelpers/document_namespace_test.go [hunk 1]
```diff
@@ -0,0 +1,70 @@
...
+				Scheme: source.FileScheme,
+				Path:   "some/path/to/place",
+			},
+			expected: "https://anchore.com/syft/file/my-name-",
+		},
+	}
+	for _, test := range tests {
+		t.Run(test.name, func(t *testing.T) {
+			actual := DocumentNamespace(test.inputName, test.srcMetadata)
+			assert.True(t, strings.HasPrefix(actual, test.expected), fmt.Sprintf("actual namespace %q", actual))
```
Comment (luhring) [inline internal/formats/common/spdxhelpers/document_namespace_test.go:61]: Are we asserting via `strings.HasPrefix` because of the UUIDs being appended to these strings?

File: internal/formats/common/spdxhelpers/document_name_test.go [hunk 2]
```diff
@@ -0,0 +1,73 @@
...
+			require.NoError(t, err)
+			assert.True(t, strings.HasPrefix(actual, test.expected), fmt.Sprintf("actual name %q", actual))
+
+			// track each scheme tested (passed or not)
+			testedSchemes.Add(string(test.srcMetadata.Scheme))
+		})
+	}
+
+	// assert all possible schemes were under test
+	assert.ElementsMatch(t, allSchemes.List(), testedSchemes.List(), "not all source.Schemes are under test")
```
Comment (luhring) [inline internal/formats/common/spdxhelpers/document_name_test.go:72]: Nice idea 👍

**Review by luhring — COMMENTED** [review]
Looks good! Just had a question for you

File: internal/formats/common/spdxhelpers/document_namespace_test.go (hunk 1 above)
Comment (wagoodman) [reply internal/formats/common/spdxhelpers/document_namespace_test.go:61]: Indeed 👍

File: internal/formats/common/spdxhelpers/document_name_test.go (hunk 2 above)
Comment (wagoodman) [reply internal/formats/common/spdxhelpers/document_name_test.go:72]: Thanks! I try to keep collections of things under test in a way where there is an automatic failure when new items are added to the collection. This one snuck by me.

File: internal/formats/common/spdxhelpers/document_namespace_test.go (hunk 1 above)
Comment (luhring) [reply internal/formats/common/spdxhelpers/document_namespace_test.go:61]: (non-blocking) It _may_ help to have a comment about that, it took me a couple minutes to realize that, but that could have just been me

**Review by luhring — APPROVED** [review]
