### PR TITLE
fix: golang PURL should include full module

### LINKED ISSUE #4316: Incorrect Go module PURL generation when module path contains /vN (e.g. /v5)
**Description**:

When generating a BOM for Go projects, Syft incorrectly parses module paths that include a version suffix like /v5 as part of the semantic version instead of the package path.

**Example:**
We use the Go module:
`github.com/golang-jwt/jwt/v5 v5.2.1
`
In the generated bom.json, Syft produces:
```
"purl": "pkg:golang/github.com/golang-jwt/jwt@v5.2.1#v5",
"bom-ref": "pkg:golang/github.com/golang-jwt/jwt@v5.2.1#v5"
```
The correct PURL should be:
`"purl": "pkg:golang/github.com/golang-jwt/jwt/v5@v5.2.1"
`

**Impact:**

- Dependency Track tools misidentify the dependency : 

Image

- The used version is not recognized correctly.
- Associated vulnerabilities and metadata are missing.

**Environment**

- Syft version:  v1.33.0
- Language: Go
- Example package: github.com/golang-jwt/jwt/v5@v5.2.1

**Expected Behavior**
Syft should preserve the module path (/v5) and produce:
`pkg:golang/github.com/golang-jwt/jwt/v5@v5.2.1
`

**Actual Behavior**
Syft outputs:
`pkg:golang/github.com/golang-jwt/jwt@v5.2.1#v5
`

### PR DESCRIPTION
**Pull request by rezmoss**
# Description

fixed wrong go module purl when module paths had version suffixes like /v5

- Fixes #4316 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] I have added unit tests that cover changed behavior
- [x] I have tested my code in common scenarios and confirmed there are no regressions
- [x] I have added comments to my code, particularly in hard-to-understand sections

### CODE REVIEW

File: syft/pkg/cataloger/golang/package.go [hunk 1]
```diff
@@ -82,9 +82,28 @@ func packageURL(moduleName, moduleVersion string) string {
...
 		namespace = fields[0]
 	default:
-		name = fields[2]
-		namespace = strings.Join(fields[0:2], "/")
-		subpath = strings.Join(fields[3:], "/")
+		lastField := fields[len(fields)-1]
+		isVersionSuffix := strings.HasPrefix(lastField, "v") && len(lastField) > 1
+		if isVersionSuffix {
+			for _, r := range lastField[1:] {
+				if r < '0' || r > '9' {
```
Comment (kzantow) [inline syft/pkg/cataloger/golang/package.go]: Would this be slightly more clear with `unicode.IsDigit(r)`?

Comment (rezmoss) [reply syft/pkg/cataloger/golang/package.go]: unicode.IsDigit() matches all kinds of digits like arabic/etc, not just 0-9, for ver suffixes we only want ascii digits, right?

**Review by kzantow — DISMISSED** [review]
I did some digging into this, are you seeing this issue when scanning source code with `go.mod` or Go binaries?

I think the `go.mod` case should have a different fix, and I think the go binary case could also have a slightly different fix. I assume we are, in fact, using the packages library now to determine the `go.mod` case, which should be returning the correct modules, that match the `go.mod`, and similarly should just use those directly rather than being split to subpaths at all.

For `go.mod`, I think we should be using the full value we found in the `go.mod` or `go.sum`, not processing it to have any subpaths -- these _are modules_ already. The subpath from the PURL spec is "used to point to a subpath inside a **package**" -- _package_, not module.

~~For the binary case, we could think about extending the [online license lookup](https://github.com/anchore/syft/blob/main/syft/pkg/cataloger/golang/licenses.go#L162-L173) to include identification of the module paths (not asking for this as part of your PR here), but default to a slightly different behavior that looks for a `/v#` _anywhere within the path_ before falling back to `<host>/<segment1>/<segment2>`, though a package with `/v#` doesn't necessarily mean the _module_ has that, we need the `go.mod` to be able to tell for sure, though I suspect most modules are good citizens and update when using this versioning scheme.~~ EDIT: I was conflating this with something else we're working on, but today with binaries, we also get _module names_, not packages, and these should similarly be used directly. At such time as we surface _packages_, we will have some additional metadata that may be output in a PURL subpath somewhere, but for all current processing we should use module names directly.

**Comment by rezmoss** [comment]
@kzantow t main issue the user reported in https://github.com/anchore/syft/issues/4316 was about go.mod, not the go binary

t purl returned something like "pkg:golang/github.com/golang-jwt/jwt@v5.3.0#v5" but it should be "pkg:golang/github.com/golang-jwt/jwt/v5@v5.2.1"

and this is the output from my implementation

Before

b2


After

b3


to reproduce, just create a go.mod file

```
module tst_gomod

go 1.25.3

require github.com/golang-jwt/jwt/v5 v5.3.0 // indirect
```

and scan

**Comment by kzantow** [comment]
@rezmoss right, read [the comment I left on the issue](https://github.com/anchore/syft/issues/4394#issuecomment-3607574838) -- I think when reading `go.mod` that we should be using the module names directly from that file, not looking for `v#` or any special processing, really. If we did that, it would solve the problem you mentioned here as well as the other, related issue.

**Comment by rezmoss** [comment]
@kzantow added new func to handle modules straight from go.mod, no processing needed, kept the original packageurl() for binary scan support, jwt/v5 and aws sdk edge cases are now handled

**Comment by kzantow** [comment]
I believe this PR will also partially fix the following Grype issues:
* https://github.com/anchore/grype/issues/3095
* https://github.com/anchore/grype/issues/2838
