### PR TITLE
npm-aliases: handle aliases for package-lock.json

### LINKED ISSUE #1314: syft fails to resolve npm package aliases
**Please provide a set of steps on how to reproduce the issue**
- Create a `package.json` with the following contents:
```
{
  "name": "tmp",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@vue/cli-service": "^5.0.8"
  }
}
```
- Generate a `package-lock.json` by running `npm install --package-lock-only`
- Run `syft .`

**What happened**:
Running `syft` on such project generates incorrect SBOM because the dependency uses a [package alias](https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-service/package.json#L35):
```
...
@vue/component-compiler-utils             3.3.0                   npm
@vue/vue-loader-v15                       npm:vue-loader@15.10.0  npm
@vue/web-component-wrapper                1.3.0                   npm
...
```

**What you expected to happen**:
I expected `syft` to correctly resolve the npm [package alias](https://github.com/npm/rfcs/blob/main/implemented/0001-package-aliases.md) (from `@vue/vue-loader-v15` to `vue-loader@15.10.0`) and recognise that my project has a dependency on `vue-loader@15.10.0`.

**Anything else we need to know?**:

**Environment**:
- Output of `syft version`:
```
Application:        syft
Version:            0.60.2
JsonSchemaVersion:  4.1.0
BuildDate:          2022-11-02T14:43:28Z
GitCommit:          35f0f2931e310882fe7117c41d57a185d72ca498
GitDescription:     v0.60.2
Platform:           linux/amd64
GoVersion:          go1.18.7
Compiler:           gc
```

- OS (e.g: `cat /etc/os-release` or similar):
```
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

### PR DESCRIPTION
**Pull request by Mikcl**
Fixes #1314 

This _only_ addresses npm/`package-lock.json` aliases.
Addresses package-lock.json version 1-3. 

the `package.json` that the `package-lock.json`s examples were derived from:
https://gist.github.com/Mikcl/aef4d180f4275b66252dca32b6668375#file-package-json

### CODE REVIEW

File: syft/pkg/cataloger/javascript/parse_package_lock.go [hunk 1]
```diff
@@ -39,6 +39,25 @@ type lockPackage struct {
 	License   string `json:"license"`
 }
 
+// Handles type aliases https://github.com/npm/rfcs/blob/main/implemented/0001-package-aliases.md
+// for npm package-lock.json version 1
+func resolvePackageLockNameAliases(name, version string) (string, string) {
+	aliasSeparator := "npm:"
```
Comment (kzantow) [inline syft/pkg/cataloger/javascript/parse_package_lock.go:45]: nit: this could be a constant

**Review by kzantow — APPROVED** [review]
Thanks @Mikcl this looks great, and thanks for adding tests 👍

File: syft/pkg/cataloger/javascript/parse_package_lock.go [hunk 2]
```diff
@@ -61,7 +80,9 @@ func parsePackageLock(resolver source.FileResolver, _ *generic.Environment, read
 
 	if lock.LockfileVersion == 1 {
 		for name, pkgMeta := range lock.Dependencies {
-			pkgs = append(pkgs, newPackageLockV1Package(resolver, reader.Location, name, pkgMeta))
+			canonicalName, canonicalVersion := resolvePackageLockNameAliases(name, pkgMeta.Version)
```
Comment (kzantow) [inline syft/pkg/cataloger/javascript/parse_package_lock.go:83]: Since this is _just_ for v1, it might be nice to just move it into the `newPackageLockV1Package` function instead of doing the `resolvePackageLockNameAliases` here

Comment (Mikcl) [reply syft/pkg/cataloger/javascript/parse_package_lock.go]: this sounds reasonable thanks.

Have moved this logic to `newPackageLockV1Package`.

Have also removed the tests for the now deleted `resolvePackageLockNameAliases`, however the same coverage is acheived with the other tests introduced in this PR.

**Comment by kzantow** [comment]
Hi @Mikcl could you `sign-off` your commits? The easiest way would be to squash to one and just sign and force push that one, probably. https://github.com/anchore/syft/blob/main/CONTRIBUTING.md#sign-off-your-work

File: syft/pkg/cataloger/javascript/package.go [hunk 3]
```diff
@@ -12,6 +12,8 @@ import (
 	"github.com/anchore/syft/syft/source"
 )
 
+const aliasSeparatorPackageLockV1 = "npm:"
```
Comment (kzantow) [inline syft/pkg/cataloger/javascript/package.go:15]: the smallest of nits: I think this would be a `prefix` rather than a `separator`, no?

**Review by kzantow — APPROVED** [review]

File: syft/pkg/cataloger/javascript/package.go (hunk 3 above)
Comment (Mikcl) [reply syft/pkg/cataloger/javascript/package.go]: nice spot: updated to `prefix`

**Review by kzantow — APPROVED** [review]
