### PR TITLE
3030 license declared spdx correction

### LINKED ISSUE #3030: LicenseDeclared not as per SPDX License List
**What happened**:
For the following package, the licenseDeclared is not as per the SPDX license list https://spdx.org/licenses/
```
        {
            "name": "libbsd",
            "SPDXID": "SPDXRef-Package-rpm-libbsd-bfec4299ebaea3ed",
            "versionInfo": "0.11.7-2.el7",
            "supplier": "Organization: Fedora Project",
            "originator": "Organization: Fedora Project",
            "downloadLocation": "NOASSERTION",
            "filesAnalyzed": true,
            "packageVerificationCode": {
                "packageVerificationCodeValue": "755d51732dcefe93fa28bb52e42df740e8aca0a0"
            },
            "sourceInfo": "acquired package info from RPM DB: /var/lib/rpm/Packages",
            "licenseConcluded": "NOASSERTION",
            "licenseDeclared": "(Beerware AND BSD-2-Clause AND BSD-3-Clause AND BSD-4-Clause AND ISC AND libutil-David-Nugent AND MIT AND LicenseRef-Fedora-Public-Domain)",
            "copyrightText": "NOASSERTION",
            "externalRefs": [
                {
                    "referenceCategory": "SECURITY",
                    "referenceType": "cpe23Type",
                    "referenceLocator": "cpe:2.3:a:fedoraproject:libbsd:0.11.7-2.el7:*:*:*:*:*:*:*"
                },
                {
                    "referenceCategory": "SECURITY",
                    "referenceType": "cpe23Type",
                    "referenceLocator": "cpe:2.3:a:libbsd:libbsd:0.11.7-2.el7:*:*:*:*:*:*:*"
                },
                {
                    "referenceCategory": "PACKAGE-MANAGER",
                    "referenceType": "purl",
                    "referenceLocator": "pkg:rpm/centos/libbsd@0.11.7-2.el7?arch=x86_64&upstream=libbsd-0.11.7-2.el7.src.rpm&distro=centos-7"
                }
            ]
        }
```
The value `LicenseRef-Fedora-Public-Domain` does not match any of the SPDX identifiers listed.

This value is causing the `ntia-checker` to generate a ValidationMessage `Unrecognized license reference: LicenseRef-Fedora-Public-Domain`.

**What you expected to happen**:
licenseDeclared field to have license values as per SPDX identifiers list.
If its a valid license, it can also be submitted to SPDX for its consideration as per: https://github.com/spdx/license-list-XML/blob/main/CONTRIBUTING.md

**Steps to reproduce the issue**:

**Anything else we need to know?**:

**Environment**:
- Output of `syft version`: syft 1.9.0
- OS (e.g: `cat /etc/os-release` or similar):  Darwin Kernel Version 23.2.0: Wed Nov 15 21:54:10 PST 2023; root:xnu-10002.61.3~2/RELEASE_X86_64 x86_64

### PR DESCRIPTION
**Pull request by spiffcs**
# Description

The syft format helpers for spdx currently treat `License-Ref-*` as a valid spdx expression. This causes our selection on `l.Value` to be partially incorrect when trying to add licenses to the `hasExtractedLicensingInfos` in the spdx document.

This change updates the spdx helpers so that singular `License-Ref` candidates are added to this section.

- Fixes #3030

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [ ] I have added unit tests that cover changed behavior
- [ ] I have tested my code in common scenarios and confirmed there are no regressions
- [ ] I have added comments to my code, particularly in hard-to-understand sections

### CODE REVIEW

File: syft/format/common/spdxhelpers/to_format_model.go [hunk 1]
```diff
@@ -742,14 +749,28 @@ func toOtherLicenses(catalog *pkg.Collection) []*spdx.OtherLicense {
...
+			ExtractedText:     value,
 		})
 	}
 	return result
 }
 
+// isSingularLicenseRef checks if the string is a singular LicenseRef-* identifier
+func isSingularLicenseRef(s string) bool {
+	// Regular expression to match LicenseRef-* format (case-sensitive)
+	re := regexp.MustCompile(`^LicenseRef-[A-Za-z0-9_-]+$`)
```
Comment (wagoodman) [inline syft/format/common/spdxhelpers/to_format_model.go:768]: no need to recompile this regex on every call of this function -- this can be a global like we do elsewhere

File: syft/format/common/spdxhelpers/to_format_model.go [hunk 2]
```diff
@@ -742,14 +749,28 @@ func toOtherLicenses(catalog *pkg.Collection) []*spdx.OtherLicense {
...
 			LicenseIdentifier: license.ID,
-			ExtractedText:     license.Value,
+			ExtractedText:     value,
 		})
 	}
 	return result
 }
 
+// isSingularLicenseRef checks if the string is a singular LicenseRef-* identifier
+func isSingularLicenseRef(s string) bool {
```
Comment (wagoodman) [inline syft/format/common/spdxhelpers/to_format_model.go:766]: this seems to detect if there is a license ref, but how does it really help determine if it's singular or not? I think I'm missing some context here

File: syft/format/common/spdxhelpers/to_format_model.go [hunk 3]
```diff
@@ -713,8 +714,8 @@ func toFileTypes(metadata *file.Metadata) (ty []string) {
 	return ty
 }
 
-// other licenses are for licenses from the pkg.Package that do not have an SPDXExpression
-// field. The spdxexpression field is only filled given a validated Value field.
+// other licenses are for licenses from the pkg.Package that do not have a valid SPDX Expression
+// OR are an expression that is a single `License-Ref-*`
```
Comment (wagoodman) [inline syft/format/common/spdxhelpers/to_format_model.go:718]: I've seen multiple references in comments and PR descriptions about `License-Ref`, but the code handles `LicenseRef`... the code looks consistent with what I think should happen, is this just an inconsistency in docs? Or a case I'm missing?

Comment (spiffcs) [reply syft/format/common/spdxhelpers/to_format_model.go:718]: The docs changed here because `The spdxexpression field is only filled given a validated Value field` is a case we must handle when we discover `License-Ref-*` as license metadata (one we did NOT create).

`License-Ref-*`, when discovered by syft, will validate as a correct SPDXExpression. Our previous logic would only act on a license in `toOtherLicenses` if `SPDXExpression == ""`.

This was missing the case where `SPDXExpression=="Licenses-Ref-*"` which would require an entry to be created for `spdx.OtherLicenses`

File: syft/format/common/spdxhelpers/to_format_model.go [hunk 4]
```diff
@@ -762,13 +762,12 @@ func toOtherLicenses(catalog *pkg.Collection) []*spdx.OtherLicense {
 	return result
 }
 
-// isSingularLicenseRef checks if the string is a singular LicenseRef-* identifier
-func isSingularLicenseRef(s string) bool {
-	// Regular expression to match LicenseRef-* format (case-sensitive)
-	re := regexp.MustCompile(`^LicenseRef-[A-Za-z0-9_-]+$`)
+var LicenseRefRegEx = regexp.MustCompile(`^LicenseRef-[A-Za-z0-9_-]+$`)
```
Comment (wagoodman) [inline syft/format/common/spdxhelpers/to_format_model.go:765]: should be unexported
