### PR TITLE
fix: handle individual cataloger panics

### LINKED ISSUE #1624: Handle cataloger panics
**What would you like to be added**:
If any single cataloger panics, the entire Syft execution terminates. It would be nice to loudly log these as `ERROR` messages but allow Syft to continue cataloging and return a result.

**Why is this needed**:
Prevent Syft from crashing and give as much information as possible to users.

**Additional context**:
There was a recent ticket, https://github.com/anchore/syft/issues/1621, in which Syft panic'd and the entire run failed, where we could have cataloged everything except a single file that caused the panic, and reported that file. This would help Syft development as well, because it would be much easier for users to point developers to failed files.

### PR DESCRIPTION
**Pull request by kzantow**
This PR handles any panics that occur within individual catalogers, allowing cataloging to continue and an SBOM to be generated.

Fixes #1624

### CODE REVIEW

File: syft/pkg/cataloger/catalog.go [hunk 1]
```diff
@@ -168,14 +175,10 @@ func Catalog(resolver source.FileResolver, release *linux.Release, parallelism i
 
 	allRelationships = append(allRelationships, pkg.NewRelationships(catalog)...)
 
-	if errs != nil {
-		return nil, nil, errs
-	}
-
 	filesProcessed.SetCompleted()
 	packagesDiscovered.SetCompleted()
```
Comment (kzantow) [inline syft/pkg/cataloger/catalog.go:179]: The fact that this function was returning _before_ the `.SetCompleted()` calls below resulted in a hung TUI for any error that occurs.

Comment (wagoodman) [reply syft/pkg/cataloger/catalog.go:179]: oh duh! man, I sent you down the hard path too soon.

Comment (wagoodman) [reply syft/pkg/cataloger/catalog.go:179]: actually, can you add a little more defensiveness to this (protecting against future changes)? Can you add something to the affect of:
```golang
defer filesProcessed.SetCompleted()
defer packagesDiscovered.SetCompleted()
```

where these are created with `newMonitor()`?

Comment (kzantow) [reply syft/pkg/cataloger/catalog.go]: Good call -- done!
