### PR TITLE
fix: identify CycloneDX JSON without $schema

### LINKED ISSUE #2299: Unable to identify CycloneDX JSON documents without $schema property
**What happened**:

syft conver failed with 0.95.0 build

```
==> /opt/homebrew/Cellar/syft/0.95.0/bin/syft convert /private/tmp/syft-test-20231107-94892-6iadn/micronaut.json
1 error occurred:
	* failed to decode SBOM: sbom format not recognized
```

**What you expected to happen**:

pass

**Steps to reproduce the issue**:

- grab release binary
- run `syft convert` against `https://raw.githubusercontent.com/anchore/syft/934644232ab115b2518acdb5d240ae31aaf55989/syft/pkg/cataloger/java/test-fixtures/graalvm-sbom/micronaut.json`

**Anything else we need to know?**:

n/a

**Environment**:
- Output of `syft version`: 0.95.0
- OS (e.g: `cat /etc/os-release` or similar): macOS (but I dont think it is relevant)

---

relates to https://github.com/Homebrew/homebrew-core/pull/153559

### PR DESCRIPTION
**Pull request by kzantow**
This PR corrects an issue that identifying CycloneDX JSON documents was being too strict, requiring the `$schema` field be present. Whether this is required or not, Syft can be a bit more lax about parsing CycloneDX JSON and just look for the `bomFormat` and `specVersion` fields.

Fixes #2299

### CODE REVIEW

**Review by willmurphyscode — APPROVED** [review]

File: syft/format/cyclonedxjson/decoder.go [hunk 1]
```diff
@@ -75,7 +74,7 @@ func (d decoder) Identify(reader io.ReadSeeker) (sbom.FormatID, string) {
 		return "", ""
 	}
 
-	id, version := getFormatInfo(doc.JSONSchema, doc.BOMFormat, doc.SpecVersion)
```
Comment (wagoodman) [inline syft/format/cyclonedxjson/decoder.go:78]: is json-schema optional?

Comment (kzantow) [reply syft/format/cyclonedxjson/decoder.go:78]: `$schema` is not valid for CycloneDX 1.2, at least: https://github.com/CycloneDX/specification/blob/1.2/schema/bom-1.2.schema.json
